# ================================================================
# Consumes:
#   - group-specific spatial network RDS from canonical spatial-network output
# Produces:
#   - differential network tables, figures, network files and RDS cache in canonical folders
# File contract:
#   - docs/active_script_io_audit.tsv object 07_spatial_networks/02_differential_networks.r
# ================================================================
# Differential spatial network analysis
# ================================================================
# Purpose:
#   Compare group-specific layer/region similarity networks generated by
#   Analysis/network_spatial_relations.r and quantify network rewiring.
#
# Required first step:
#   Run Analysis/network_spatial_relations.r with run_group_specific_networks = TRUE.
#
# Main outputs:
#   - Edge-level delta tables for CON vs RES, CON vs SUS, RES vs SUS
#   - Gain/loss/strengthened/weakened edge calls
#   - Node-level rewiring summaries
#   - Differential network plots
#   - Cytoscape-compatible node/edge CSV files
# ================================================================

paths_file <- if (file.exists(file.path("R", "paths.R"))) file.path("R", "paths.R") else file.path("..", "R", "paths.R")
source(paths_file)
MODULE_ID <- "07_spatial_networks"
SUBSTEP_ID <- "differential_networks"
CANONICAL_PATHS <- create_module_dirs(MODULE_ID, SUBSTEP_ID)

required_pkgs <- c("dplyr", "tidyr", "stringr", "purrr", "tibble", "ggplot2", "igraph", "ggraph", "openxlsx", "svglite")
missing <- required_pkgs[!vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing) > 0) stop("Missing required R package(s): ", paste(missing, collapse = ", "), ". Install them explicitly before running this script.", call. = FALSE)
invisible(lapply(required_pkgs, library, character.only = TRUE))

params <- list(
  spatial_rds = path_processed("07_spatial_networks", "network_spatial_relations", "network_spatial_relations_objects.rds"),
  output_dir = CANONICAL_PATHS$reports,
  group_order = c("CON", "RES", "SUS"),
  comparisons = list(c("CON", "RES"), c("CON", "SUS"), c("RES", "SUS")),
  edge_presence_abs_r = 0.50,
  delta_abs_r_threshold = 0.10,
  plot_min_abs_delta = 0.10
)

if (is_dry_run()) {
  dry_run_line("Script", "07_spatial_networks/02_differential_networks.r")
  dry_run_line("Spatial RDS", params$spatial_rds, if (file.exists(params$spatial_rds)) "PASS" else "FAIL")
  dry_run_line("Output folders", paste(unlist(CANONICAL_PATHS), collapse = "; "))
  quit(status = if (file.exists(params$spatial_rds)) 0 else 1, save = "no")
}
if (!file.exists(params$spatial_rds)) stop("spatial_rds not found: ", params$spatial_rds, call. = FALSE)

message2 <- function(...) message(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), " | ", ...)
safe_name <- function(x) stringr::str_replace_all(x, "[^A-Za-z0-9_\\-]+", "_")

make_dirs <- function(base_dir) {
  dirs <- list(
    base = base_dir,
    tables = CANONICAL_PATHS$tables,
    figures = CANONICAL_PATHS$figures,
    networks = file.path(CANONICAL_PATHS$processed, "network_files"),
    logs = CANONICAL_PATHS$logs
  )
  invisible(lapply(dirs, dir.create, recursive = TRUE, showWarnings = FALSE))
  dirs
}

get_group_cor_matrix <- function(obj, group) {
  if (is.null(obj$group_specific) || is.null(obj$group_specific[[group]])) return(NULL)
  obj$group_specific[[group]]$spearman$cor_mat
}

matrix_to_edges <- function(cor_mat, group) {
  units <- colnames(cor_mat)
  expand.grid(Source = units, Target = units, stringsAsFactors = FALSE) %>%
    tibble::as_tibble() %>%
    dplyr::filter(.data$Source < .data$Target) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(SpearmanR = cor_mat[.data$Source, .data$Target]) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(Group = group, AbsSpearmanR = abs(.data$SpearmanR))
}

compare_edge_sets <- function(edges_a, edges_b, group_a, group_b, params) {
  ea <- edges_a %>%
    dplyr::transmute(Source = .data$Source, Target = .data$Target, R_A = .data$SpearmanR, AbsR_A = .data$AbsSpearmanR)
  eb <- edges_b %>%
    dplyr::transmute(Source = .data$Source, Target = .data$Target, R_B = .data$SpearmanR, AbsR_B = .data$AbsSpearmanR)

  dplyr::full_join(ea, eb, by = c("Source", "Target")) %>%
    dplyr::mutate(
      R_A = dplyr::coalesce(.data$R_A, 0),
      R_B = dplyr::coalesce(.data$R_B, 0),
      AbsR_A = dplyr::coalesce(.data$AbsR_A, 0),
      AbsR_B = dplyr::coalesce(.data$AbsR_B, 0),
      Group_A = group_a,
      Group_B = group_b,
      DeltaR = .data$R_B - .data$R_A,
      AbsDeltaR = abs(.data$DeltaR),
      Present_A = .data$AbsR_A >= params$edge_presence_abs_r,
      Present_B = .data$AbsR_B >= params$edge_presence_abs_r,
      EdgeClass = dplyr::case_when(
        .data$Present_A & !.data$Present_B ~ "lost_in_B",
        !.data$Present_A & .data$Present_B ~ "gained_in_B",
        .data$Present_A & .data$Present_B & .data$DeltaR >= params$delta_abs_r_threshold ~ "strengthened_in_B",
        .data$Present_A & .data$Present_B & .data$DeltaR <= -params$delta_abs_r_threshold ~ "weakened_in_B",
        .data$Present_A & .data$Present_B ~ "preserved",
        TRUE ~ "weak_in_both"
      ),
      DirectionChange = dplyr::case_when(
        sign(.data$R_A) != sign(.data$R_B) & abs(.data$R_A) >= params$edge_presence_abs_r & abs(.data$R_B) >= params$edge_presence_abs_r ~ "sign_flip_strong_edges",
        sign(.data$R_A) != sign(.data$R_B) ~ "sign_flip_weak_edge",
        TRUE ~ "same_sign"
      )
    ) %>%
    dplyr::arrange(dplyr::desc(.data$AbsDeltaR))
}

node_rewiring_summary <- function(diff_edges) {
  if (nrow(diff_edges) == 0) {
    return(tibble::tibble(
      Node = character(), N_Edges = integer(), N_Gained = integer(),
      N_Lost = integer(), N_Strengthened = integer(), N_Weakened = integer(),
      MeanAbsDeltaR = numeric(), MaxAbsDeltaR = numeric(), NetDeltaR = numeric()
    ))
  }

  dplyr::bind_rows(
    diff_edges %>% dplyr::transmute(Node = .data$Source, EdgeClass = .data$EdgeClass, AbsDeltaR = .data$AbsDeltaR, DeltaR = .data$DeltaR),
    diff_edges %>% dplyr::transmute(Node = .data$Target, EdgeClass = .data$EdgeClass, AbsDeltaR = .data$AbsDeltaR, DeltaR = .data$DeltaR)
  ) %>%
    dplyr::group_by(.data$Node) %>%
    dplyr::summarise(
      N_Edges = dplyr::n(),
      N_Gained = sum(.data$EdgeClass == "gained_in_B", na.rm = TRUE),
      N_Lost = sum(.data$EdgeClass == "lost_in_B", na.rm = TRUE),
      N_Strengthened = sum(.data$EdgeClass == "strengthened_in_B", na.rm = TRUE),
      N_Weakened = sum(.data$EdgeClass == "weakened_in_B", na.rm = TRUE),
      MeanAbsDeltaR = mean(.data$AbsDeltaR, na.rm = TRUE),
      MaxAbsDeltaR = max(.data$AbsDeltaR, na.rm = TRUE),
      NetDeltaR = sum(.data$DeltaR, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    dplyr::arrange(dplyr::desc(.data$MaxAbsDeltaR), dplyr::desc(.data$MeanAbsDeltaR))
}

plot_differential_network <- function(diff_edges, outfile, title, params) {
  plot_edges <- diff_edges %>%
    dplyr::filter(.data$AbsDeltaR >= params$plot_min_abs_delta) %>%
    dplyr::filter(.data$EdgeClass != "weak_in_both")

  if (nrow(plot_edges) == 0) {
    warning("No differential edges to plot for ", title)
    return(invisible(NULL))
  }

  nodes <- unique(c(plot_edges$Source, plot_edges$Target)) %>%
    tibble::tibble(name = .) %>%
    dplyr::filter(!is.na(.data$name), .data$name != "") %>%
    dplyr::distinct(.data$name, .keep_all = TRUE)

  g <- igraph::graph_from_data_frame(
    plot_edges %>% dplyr::transmute(from = .data$Source, to = .data$Target, AbsDeltaR = .data$AbsDeltaR, DeltaR = .data$DeltaR, EdgeClass = .data$EdgeClass),
    directed = FALSE,
    vertices = nodes
  )

  p <- ggraph::ggraph(g, layout = "fr") +
    ggraph::geom_edge_link(aes(width = AbsDeltaR, linetype = EdgeClass, alpha = AbsDeltaR), colour = "grey35") +
    ggraph::geom_node_point(shape = 21, fill = "white", colour = "black", size = 4, stroke = 0.4) +
    ggraph::geom_node_text(aes(label = name), repel = TRUE, size = 2.8) +
    ggraph::scale_edge_width(range = c(0.2, 1.8), guide = "none") +
    ggraph::scale_edge_alpha(range = c(0.25, 0.9), guide = "none") +
    ggplot2::labs(title = title) +
    ggplot2::theme_void(base_size = 8) +
    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, face = "bold"))

  ggplot2::ggsave(outfile, p, width = 150, height = 120, units = "mm", device = svglite::svglite)
  invisible(p)
}

make_cytoscape_edges <- function(diff_edges, params) {
  out <- diff_edges %>%
    dplyr::filter(
      .data$AbsDeltaR >= params$plot_min_abs_delta,
      .data$EdgeClass != "weak_in_both"
    ) %>%
    dplyr::transmute(
      Source = .data$Source,
      Target = .data$Target,
      DeltaR = .data$DeltaR,
      AbsDeltaR = .data$AbsDeltaR,
      EdgeClass = .data$EdgeClass,
      DirectionChange = .data$DirectionChange,
      R_A = .data$R_A,
      R_B = .data$R_B
    )

  required_cols <- c("Source", "Target", "DeltaR", "AbsDeltaR", "EdgeClass", "DirectionChange", "R_A", "R_B")
  missing_cols <- setdiff(required_cols, names(out))
  if (length(missing_cols) > 0) out[missing_cols] <- NA
  out[, required_cols, drop = FALSE]
}

make_cytoscape_nodes <- function(cyt_edges, node_summary) {
  if (nrow(cyt_edges) == 0) {
    return(tibble::tibble(name = character()))
  }

  unique(c(cyt_edges$Source, cyt_edges$Target)) %>%
    tibble::tibble(name = .) %>%
    dplyr::filter(!is.na(.data$name), .data$name != "") %>%
    dplyr::distinct(.data$name, .keep_all = TRUE) %>%
    dplyr::left_join(node_summary, by = c("name" = "Node")) %>%
    dplyr::select("name", dplyr::everything())
}

write_graphml <- function(edges, nodes, outfile) {
  if (nrow(edges) == 0) return(invisible(NULL))

  nodes <- nodes %>%
    dplyr::select("name", dplyr::everything()) %>%
    dplyr::filter(!is.na(.data$name), .data$name != "") %>%
    dplyr::distinct(.data$name, .keep_all = TRUE)

  if (nrow(nodes) == 0) return(invisible(NULL))

  g <- igraph::graph_from_data_frame(
    edges %>% dplyr::rename(from = .data$Source, to = .data$Target),
    directed = FALSE,
    vertices = nodes
  )
  igraph::write_graph(g, outfile, format = "graphml")
}

# -------------------------------
# Main
# -------------------------------
dirs <- make_dirs(params$output_dir)
write_session_info(file.path(dirs$logs, "sessionInfo.txt"))
log_file <- file.path(dirs$logs, paste0("differential_networks_run_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".txt"))
sink(log_file, split = TRUE)
on.exit(sink(), add = TRUE)

message2("Starting differential spatial network analysis")
if (!file.exists(params$spatial_rds)) stop("spatial_rds not found. Run network_spatial_relations.r first: ", params$spatial_rds)
obj <- readRDS(params$spatial_rds)

all_group_edges <- purrr::map_dfr(params$group_order, function(grp) {
  mat <- get_group_cor_matrix(obj, grp)
  if (is.null(mat)) return(tibble::tibble())
  matrix_to_edges(mat, grp)
})

if (nrow(all_group_edges) == 0) stop("No group-specific correlation matrices found in spatial RDS.")
utils::write.csv(all_group_edges, file.path(dirs$tables, "all_group_edges_long.csv"), row.names = FALSE)

all_diff <- list()
all_node <- list()
wb <- openxlsx::createWorkbook()
openxlsx::addWorksheet(wb, "All_Group_Edges")
openxlsx::writeData(wb, "All_Group_Edges", all_group_edges)

for (cmp in params$comparisons) {
  group_a <- cmp[1]
  group_b <- cmp[2]
  message2("Comparing ", group_a, " vs ", group_b)

  edges_a <- all_group_edges %>% dplyr::filter(.data$Group == group_a)
  edges_b <- all_group_edges %>% dplyr::filter(.data$Group == group_b)
  if (nrow(edges_a) == 0 || nrow(edges_b) == 0) next

  diff_edges <- compare_edge_sets(edges_a, edges_b, group_a, group_b, params)
  node_summary <- node_rewiring_summary(diff_edges)
  label <- paste0(group_a, "_vs_", group_b)

  utils::write.csv(diff_edges, file.path(dirs$tables, paste0(label, "_edge_rewiring.csv")), row.names = FALSE)
  utils::write.csv(node_summary, file.path(dirs$tables, paste0(label, "_node_rewiring.csv")), row.names = FALSE)

  plot_differential_network(
    diff_edges,
    file.path(dirs$figures, paste0(label, "_differential_network.svg")),
    paste0("Spatial network rewiring: ", group_a, " vs ", group_b),
    params
  )

  cyt_edges <- make_cytoscape_edges(diff_edges, params)
  cyt_nodes <- make_cytoscape_nodes(cyt_edges, node_summary)

  utils::write.csv(cyt_edges, file.path(dirs$networks, paste0(label, "_cytoscape_edges.csv")), row.names = FALSE)
  utils::write.csv(cyt_nodes, file.path(dirs$networks, paste0(label, "_cytoscape_nodes.csv")), row.names = FALSE)
  write_graphml(cyt_edges, cyt_nodes, file.path(dirs$networks, paste0(label, ".graphml")))

  openxlsx::addWorksheet(wb, paste0(label, "_Edges"))
  openxlsx::writeData(wb, paste0(label, "_Edges"), diff_edges)
  openxlsx::addWorksheet(wb, paste0(label, "_Nodes"))
  openxlsx::writeData(wb, paste0(label, "_Nodes"), node_summary)

  all_diff[[label]] <- diff_edges
  all_node[[label]] <- node_summary
}

summary_tbl <- purrr::imap_dfr(all_diff, function(df, label) {
  df %>%
    dplyr::count(.data$EdgeClass, name = "N") %>%
    dplyr::mutate(Comparison = label) %>%
    dplyr::select("Comparison", "EdgeClass", "N")
})

utils::write.csv(summary_tbl, file.path(dirs$tables, "rewiring_summary_counts.csv"), row.names = FALSE)
openxlsx::addWorksheet(wb, "Summary")
openxlsx::writeData(wb, "Summary", summary_tbl)
openxlsx::saveWorkbook(wb, file.path(dirs$tables, "differential_networks_summary.xlsx"), overwrite = TRUE)

saveRDS(
  list(params = params, all_group_edges = all_group_edges, differential_edges = all_diff, node_rewiring = all_node, summary = summary_tbl, sessionInfo = sessionInfo()),
  file.path(dirs$logs, "differential_networks_objects.rds")
)
write_run_manifest(
  file.path(dirs$logs, "run_manifest.yml"),
  inputs = list(spatial_rds = params$spatial_rds),
  outputs = list(tables = dirs$tables, figures = dirs$figures, networks = dirs$networks, rds = file.path(dirs$logs, "differential_networks_objects.rds")),
  parameters = params,
  notes = "Captures edge presence and delta thresholds for differential spatial network calls."
)

message2("Finished differential spatial network analysis")
message2("Caution: rewiring is descriptive unless supported by bootstrap stability or independent validation.")
