#!/usr/bin/env Rscript

# Part B, sections 14 (graph rendering), 16-18, 20 and 22.
#
# AUDIT ONLY. Reads the inventory and edge list produced by
# 04_architecture_inventory.R and adds the output model, the publication-layer
# review, the helper-library organisation, the identity-versus-display-label
# contract and the source-data-first check.

setwd("S:/Lab_Member/Tobi/Experiments/Exp9_Social-Stress/Analysis/proteomics")
source("99_audits/publication_hardening/00_checkpoint.R")
suppressMessages({library(ggplot2); library(yaml)})

PH_FIG <- file.path(PH_OUT, "figures")
dir.create(PH_FIG, recursive = TRUE, showWarnings = FALSE)
rd <- function(f) utils::read.csv(file.path(PH_TAB, f), stringsAsFactors = FALSE)
inv <- rd("repository_architecture_inventory.csv")
edges <- rd("repository_dependency_edges.csv")

# ================================================= B14 layer dependency graph
#
# 843 file-level edges do not render legibly, and the question this graph has to
# answer is about layers, not files: which layer may depend on which. The edge
# list stays the file-level record; the figure is its layer aggregation.
LORDER <- c("configuration", "shared helper library", "numbered analysis stage",
            "figure / manuscript layer", "audit layer", "test suite",
            "developer tooling", "testing scaffold", "deprecated",
            "repository root", "packaged assets", "other")
agg <- as.data.frame(table(from = edges$from_layer[edges$to_exists],
                           to = edges$to_layer[edges$to_exists]),
                     stringsAsFactors = FALSE)
agg <- agg[agg$Freq > 0, ]
agg$from <- factor(agg$from, levels = rev(LORDER[LORDER %in% agg$from]))
agg$to <- factor(agg$to, levels = LORDER[LORDER %in% agg$to])

# the rule the figure is testing: a publication path must not depend downward on
# a scaffold, a deprecated file or a test
FORBIDDEN_TO <- c("deprecated", "testing scaffold", "test suite")
PRODUCER <- c("numbered analysis stage", "figure / manuscript layer",
              "shared helper library", "configuration")
agg$violation <- as.character(agg$to) %in% FORBIDDEN_TO &
                 as.character(agg$from) %in% PRODUCER

p <- ggplot(agg, aes(x = to, y = from, fill = Freq)) +
  geom_tile(colour = "white", linewidth = 0.4) +
  geom_text(aes(label = Freq, colour = violation), size = 2.4,
            show.legend = FALSE) +
  scale_fill_gradient(low = "#eef3f8", high = "#2c5f8a", name = "source() edges") +
  scale_colour_manual(values = c(`FALSE` = "grey15", `TRUE` = "#b2182b")) +
  labs(title = "Active dependency graph, aggregated by layer",
       subtitle = paste0("Row sources column. ", sum(agg$Freq),
                         " resolved source() edges; ", sum(agg$violation),
                         " producer-to-scaffold edges."),
       x = "depends on", y = "layer") +
  theme_minimal(base_size = 7, base_family = "sans") +
  theme(axis.text.x = element_text(angle = 40, hjust = 1),
        panel.grid = element_blank(),
        plot.title = element_text(face = "bold", size = 8))
ggsave(file.path(PH_FIG, "repository_dependency_graph.svg"), p,
       width = 130, height = 85, units = "mm", device = "svg")

# ======================================================== B16 output model
OUT_ROOTS <- list.dirs("results", recursive = FALSE, full.names = FALSE)
structured <- c("tables", "figures", "reports", "source_data", "audit", "logs",
                "manuscript", "module_scores", "reviewer_audit")
om <- data.frame(
  output_root = OUT_ROOTS,
  class = ifelse(OUT_ROOTS %in% structured, "structured output root",
                 "ad-hoc one-off output root"),
  tracked_in_git = vapply(OUT_ROOTS, function(d)
    length(system2("git", c("ls-files", shQuote(file.path("results", d))),
                   stdout = TRUE)) > 0, logical(1)),
  stringsAsFactors = FALSE)
om$migration_risk <- ifelse(om$tracked_in_git, "review - tracked content",
                            "none - untracked, regenerated by the pipeline")
rownames(om) <- NULL
utils::write.csv(om, file.path(PH_TAB, "repository_output_model.csv"),
                 row.names = FALSE)

# ==================================================== B17 publication layer
#
# Each manuscript layer is identified by its renderer prefix. Only one of them
# is current; the rest are superseded but must remain readable, because the
# frozen figures were produced by the code as it stood.
LAYERS <- rbind(
  data.frame(prefix = "f9_", layer = "final_truth_v9", status = "CURRENT"),
  data.frame(prefix = "s9f_", layer = "final_truth_v9 engine", status = "CURRENT"),
  data.frame(prefix = "e8_", layer = "editorial_v8", status = "SUPERSEDED"),
  data.frame(prefix = "nf_", layer = "nature_final_v7", status = "SUPERSEDED"),
  data.frame(prefix = "nvp_", layer = "nature_v2", status = "SUPERSEDED"),
  data.frame(prefix = "s6_", layer = "spatial_v6", status = "SUPERSEDED"),
  data.frame(prefix = "s5_", layer = "story_v5", status = "SUPERSEDED"))
fig_files <- inv$path[inv$layer == "figure / manuscript layer"]
r_files <- inv$path[inv$layer == "shared helper library"]
LAYERS$renderer_definitions <- vapply(LAYERS$prefix, function(px) {
  sum(vapply(c(fig_files, r_files), function(f)
    length(grep(paste0("^", px, "[a-z0-9_]* <- function"),
                readLines(f, warn = FALSE))), integer(1)))
}, integer(1))

# which renderers the frozen v9 contract actually calls, and from which layer
CT <- yaml::read_yaml("figures/figure_final_truth_v9_contract.yml")
used <- unique(vapply(CT$panels, function(p)
  as.character(p$renderer %||% ""), character(1)))
used <- used[nzchar(used)]
LAYERS$renderers_used_by_v9_contract <- vapply(LAYERS$prefix, function(px)
  sum(grepl(paste0("^", px), used)), integer(1))
LAYERS$verdict <- ifelse(
  LAYERS$status == "CURRENT", "authoritative",
  ifelse(LAYERS$renderers_used_by_v9_contract > 0,
         "SUPERSEDED BUT STILL REACHED BY THE FROZEN CONTRACT",
         "superseded and unreached - retain as history"))
utils::write.csv(LAYERS, file.path(PH_TAB, "publication_layer_review.csv"),
                 row.names = FALSE)

# ============================================== B18 helper-library organisation
fam <- data.frame(file = basename(r_files), path = r_files,
                  stringsAsFactors = FALSE)
fam$family <- ifelse(
  grepl("^(final_truth_v9|s9f)", fam$file), "final_truth_v9",
  ifelse(grepl("^editorial_v8", fam$file), "editorial_v8",
  ifelse(grepl("^nature_final", fam$file), "nature_final_v7",
  ifelse(grepl("^nature_v2", fam$file), "nature_v2",
  ifelse(grepl("^(spatial|story)", fam$file), "spatial_v6 / story_v5",
  ifelse(grepl("^wgcna|module", fam$file), "wgcna",
  ifelse(grepl("^(paths|dataset|pipeline|null_coalescing|xlsx)", fam$file),
         "infrastructure", "analysis helpers")))))))
fam$fan_in <- vapply(fam$path, function(p) sum(edges$to == p), integer(1))
# A helper can also be reached through a variable - audit_src <- repo_path(...)
# then source(audit_src) - or through testthat::test_path, neither of which the
# edge extractor resolves. A second pass over plain text catches those, so that
# "no source() edge" is not mistaken for "unused".
named_elsewhere <- vapply(fam$file, function(f) {
  hits <- suppressWarnings(system2("git", c("grep", "-l", "-F", shQuote(f),
                                            "--", "*.R", "*.r", "*.yml"),
                                   stdout = TRUE, stderr = FALSE))
  length(setdiff(hits, file.path("R", f))) > 0
}, logical(1))
fam$named_outside_itself <- named_elsewhere
fam$reachability <- ifelse(fam$fan_in > 0, "sourced directly",
  ifelse(fam$named_outside_itself, "reached indirectly (variable or test_path)",
         "UNREFERENCED"))
fam <- fam[order(fam$family, -fam$fan_in), ]
rownames(fam) <- NULL
utils::write.csv(fam, file.path(PH_TAB, "helper_library_families.csv"),
                 row.names = FALSE)
orphan <- fam[fam$reachability == "UNREFERENCED", ]

# ======================================= B20 identity vs display label contract
#
# The registry is the identity; SHORT in the renderer is the display label. A
# display label may be shorter than the identity, but there must be exactly one
# display label per identity and no identity without one.
reg <- utils::read.csv("config/manuscript_go_theme_registry.tsv", sep = "\t",
                       stringsAsFactors = FALSE)
# qc_review rows (display_order 90+) are deliberately not drawn on the atlas;
# only primary rows owe a display label.
prim <- reg[reg$theme_role == "primary" &
            reg$match_scope != "exclude_anchor_and_descendants", , drop = FALSE]
pan <- readLines("R/final_truth_v9_panels.R", warn = FALSE)
b <- grep("^  SHORT <- c\\(", pan)
e <- b + which(grepl("\\)\\s*$", pan[b:(b + 20)]))[1] - 1L
short_src <- paste(pan[b:e], collapse = " ")
short_ids <- gsub(".*?([a-z0-9_]+) = \".*", "\\1",
                  regmatches(short_src, gregexpr("[a-z0-9_]+ = \"[^\"]*\"",
                                                 short_src))[[1]])
short_lab <- gsub(".*= \"([^\"]*)\".*", "\\1",
                  regmatches(short_src, gregexpr("[a-z0-9_]+ = \"[^\"]*\"",
                                                 short_src))[[1]])
ids <- unique(prim$theme_id)
idc <- data.frame(
  theme_id = ids,
  registry_display_label = prim$display_label[match(ids, prim$theme_id)],
  renderer_short_label = short_lab[match(ids, short_ids)],
  stringsAsFactors = FALSE)
idc$has_display_label <- !is.na(idc$renderer_short_label)
idc$order_matches_registry <- seq_along(ids) == match(ids, short_ids)
extra <- setdiff(short_ids, ids)
utils::write.csv(idc, file.path(PH_TAB, "identity_display_label_contract.csv"),
                 row.names = FALSE)

# =============================================== B22 source-data-first contract
#
# Every publication panel must be reproducible from a released source-data file
# alone. The inventory already resolved those paths; this restates it as a rule
# with its exceptions named.
reach <- rd("manuscript_reachability_inventory.csv")
sdf <- data.frame(
  rule = c("every panel has a released source-data CSV",
           "every panel has a vector SVG",
           "every panel names its renderer",
           "every renderer is defined in a current v9 layer file"),
  n_panels = nrow(reach),
  n_satisfying = c(sum(reach$source_data_path != "MISSING"),
                   sum(reach$panel_svg == "present"),
                   sum(nzchar(reach$renderer)),
                   sum(reach$renderer_file != "not located")),
  stringsAsFactors = FALSE)
sdf$n_failing <- sdf$n_panels - sdf$n_satisfying
sdf$status <- ifelse(sdf$n_failing == 0, "PASS", "REVIEW")
utils::write.csv(sdf, file.path(PH_TAB, "source_data_first_contract.csv"),
                 row.names = FALSE)

cat("\n===== PART B LAYER REVIEW =====\n")
cat("B14 layer graph:", sum(agg$Freq), "resolved edges |",
    sum(agg$violation), "producer-to-scaffold edges -> ",
    file.path(PH_FIG, "repository_dependency_graph.svg"), "\n")
cat("\nB16 output roots:\n"); print(om[, c("output_root", "class", "tracked_in_git")])
cat("\nB17 publication layers:\n")
print(LAYERS[, c("layer", "status", "renderer_definitions",
                 "renderers_used_by_v9_contract", "verdict")])
cat("\nB18 helper families:\n"); print(table(fam$family))
print(table(fam$reachability))
cat("unreferenced helpers:", nrow(orphan), "\n")
if (nrow(orphan)) print(orphan$file)
cat("\nB20 identity/display contract:\n"); print(idc)
cat("display labels with no registry identity:",
    if (length(extra)) paste(extra, collapse = ", ") else "none", "\n")
cat("\nB22 source-data-first:\n"); print(sdf)
