#!/usr/bin/env Rscript

# Manuscript phase 1: provenance tables for the drafted Results.
#
# Every quantitative statement in Results 2 and 3 gets a row here, with the file,
# column and row key it came from. Written as a script rather than by hand so the
# tables can be regenerated and diffed, and so a number cannot enter the
# manuscript without a source.
#
# WRITES ONLY manuscript/*.csv. Touches no scientific output.

setwd("S:/Lab_Member/Tobi/Experiments/Exp9_Social-Stress/Analysis/proteomics")
MS <- "manuscript"
dir.create(MS, recursive = TRUE, showWarnings = FALSE)

SD <- "results/source_data/manuscript_candidates/final_truth_v9"
TB <- "results/tables"

S <- function(id, section, sentence, quantity, value, unit, file, column, key,
              panel, class, verified = "VERIFIED_FROM_SOURCE")
  data.frame(statement_id = id, manuscript_section = section,
             draft_sentence = sentence, quantity = quantity, value = value,
             unit = unit, source_file = file, source_column = column,
             source_key = key, figure_panel = panel, claim_type = class,
             verified = verified, stringsAsFactors = FALSE)

R2 <- "Results 2 (Figure 2)"; R3 <- "Results 3 (Figure 3)"
prov <- rbind(
  # ---------------------------------------------------------------- Results 2
  S("S2-01", R2, "323 spatial acquisitions from nine animals", "acquisitions",
    "323", "acquisitions", file.path(SD, "figure_02/v9_depth_source_data.csv"),
    "row count", "all rows", "F2b", "DESCRIPTIVE"),
  S("S2-02", R2, "180 neuropil, 71 neuronal soma and 72 microglia-enriched ROI",
    "acquisitions per compartment", "180 / 71 / 72", "acquisitions",
    file.path(SD, "figure_02/v9_depth_source_data.csv"), "dataset",
    "table(dataset)", "F2b", "DESCRIPTIVE"),
  S("S2-03", R2, "median of 4,668, 5,307 and 4,850 protein groups per acquisition",
    "median identification depth", "4668 / 5307 / 4850.5", "protein groups",
    file.path(SD, "figure_02/v9_depth_source_data.csv"), "proteins_identified",
    "median by dataset", "F2b", "DESCRIPTIVE"),
  S("S2-04", R2, "matrices comprised 5,054, 5,538 and 5,229 protein groups",
    "analysis-matrix size", "5054 / 5538 / 5229", "protein groups",
    "data/processed/01_preprocessing", "matrix dim",
    "per compartment after 70% missingness filter", "F2b", "DESCRIPTIVE"),
  # S2-05 removed after red-team: the union figure 5,694 could not be
  # re-derived from a named source (the joint-QC audit gives 5,621). The
  # sentence no longer cites a union count.
  S("S2-06", R2, "4,242 protein groups quantified across all three compartments",
    "joint matrix size", "4242", "protein groups",
    file.path(SD, "figure_02/v9_pca_source_data.csv"), "feature space",
    "joint three-compartment matrix", "F2c", "DESCRIPTIVE"),
  S("S2-07", R2, "first two components captured 45.1% and 9.8% of the variance",
    "variance explained", "0.4509 / 0.0978", "fraction",
    file.path(SD, "figure_02/v9_pca_source_data.csv"), "PC1/PC2 variance",
    "joint PCA", "F2c", "DESCRIPTIVE"),
  # The P values that originally accompanied S2-08/S2-09 were removed after
  # red-team: F2c is declared descriptive with no test, and their degrees of
  # freedom come from 323 acquisitions, which the same paragraph declares are
  # not independent replicates. The eta-squared values carry the claim.
  S("S2-08", R2, "compartment accounted for essentially all variance along PC1",
    "compartment eta-squared on PC1", "0.9559", "eta^2",
    file.path(TB, "manuscript_candidates/final_truth_v9/audit"),
    "eta_sq", "term = compartment, PC1; acquisition-level", "F2c",
    "DESCRIPTIVE"),
  S("S2-09", R2, "whereas experimental group accounted for effectively none",
    "stress-group eta-squared on PC1", "8.53e-05", "eta^2",
    file.path(TB, "manuscript_candidates/final_truth_v9/audit"),
    "eta_sq", "term = experimental group, PC1; acquisition-level", "F2c",
    "DESCRIPTIVE"),
  S("S2-10", R2, "19 protein rows resolved the 18 spatial units",
    "fingerprint rows / units / cells", "19 rows; 18 units; 378 cells", "count",
    file.path(SD, "figure_02/v9_fingerprint_source_data.csv"), "gene / spatial_unit",
    "all rows", "F2d", "DESCRIPTIVE"),
  S("S2-11", R2, "eleven prespecified control-only anatomical contrasts",
    "prespecified CON-only contrasts", "11", "contrasts",
    file.path(SD, "figure_02/v9_fingerprint_source_data.csv"), "contrast",
    "complete prespecified set", "F2d", "DESCRIPTIVE"),
  S("S2-12", R2, "ten prespecified compartment markers",
    "marker proteins", "10 (4 soma, 3 neuropil, 3 microglia/PVM)", "proteins",
    file.path(SD, "figure_02/v9_compartment_source_data.csv"), "gene",
    "all rows", "F2e", "DESCRIPTIVE"),
  # S2-13..S2-17 rewritten after red-team. The original rows supported a claim
  # that bilateral concordance depends on anatomical SCALE and that the low tail
  # is CA1-specific. Re-derivation from the source table refuted both: the
  # regional and laminar medians are indistinguishable (0.7378 vs 0.7383), and
  # four non-CA1 contrasts fall below CA1-SLM. The discriminating factor is
  # measurement COMPARTMENT.
  S("S2-13", R2, "eleven prespecified contrasts; four microglia regional-context",
    "bilateral contrast inventory", "15 rows: 11 manuscript_locked, 4 not",
    "contrasts",
    file.path(TB, "11_spatial_systems/bilateral/bilateral_spatial_identity_summary.csv"),
    "manuscript_locked", "TRUE = 11 (7 neuropil + 4 soma); FALSE = 4 microglia",
    "F2f", "DESCRIPTIVE"),
  S("S2-14", R2, "neuronal-soma regional contrasts (median 0.80, range 0.72-0.92)",
    "soma bilateral concordance", "median 0.8021; range 0.7185-0.9182",
    "Pearson r",
    file.path(TB, "11_spatial_systems/bilateral/bilateral_spatial_identity_summary.csv"),
    "pearson_r", "dataset == neuron_soma (n = 4)", "F2f", "DESCRIPTIVE"),
  S("S2-15", R2, "intermediate and widest in the neuropil (median 0.74, range 0.38-0.85)",
    "neuropil bilateral concordance", "median 0.7383; range 0.3811-0.8531",
    "Pearson r",
    file.path(TB, "11_spatial_systems/bilateral/bilateral_spatial_identity_summary.csv"),
    "pearson_r", "dataset == neuron_neuropil (n = 7)", "F2f", "DESCRIPTIVE"),
  S("S2-16", R2, "lowest for the microglia-enriched ROI (median 0.56, range 0.50-0.76)",
    "microglia bilateral concordance", "median 0.5587; range 0.4951-0.7570",
    "Pearson r",
    file.path(TB, "11_spatial_systems/bilateral/bilateral_spatial_identity_summary.csv"),
    "pearson_r", "dataset == microglia (n = 4)", "F2f", "LIMITATION"),
  S("S2-17", R2, "two lowest values were CA1 stratum oriens (0.38) and radiatum (0.49); CA1-SLM (0.74) at the median",
    "CA1 laminar concordance", "SO 0.3811; SR 0.4868; SLM 0.7383", "Pearson r",
    file.path(TB, "11_spatial_systems/bilateral/bilateral_spatial_identity_summary.csv"),
    "pearson_r", "CA1 SO / SR / SLM vs mean other CA1 strata", "F2f",
    "LIMITATION"),
  S("S2-17b", R2, "dentate-gyrus layer contrasts reproduced as well as the better regional contrasts (r = 0.81)",
    "DG laminar concordance", "0.8145 (both DG rows identical to 7 dp)",
    "Pearson r",
    file.path(TB, "11_spatial_systems/bilateral/bilateral_spatial_identity_summary.csv"),
    "pearson_r",
    "DG_MO and DG_PO vs mean other DG layers; DG neuropil has two layers so these are mirror images",
    "F2f", "DESCRIPTIVE"),
  S("S2-18", R2, "raised the intraclass correlation from 0.33 to 0.50 / 0.32 to 0.48",
    "ICC single hemisphere -> bilateral mean",
    "compartment 0.3309->0.4972; markers 0.32->0.48", "ICC",
    file.path(SD, "extended_data/v9_ed_precision_source_data.csv"),
    "ICC_single_side / ICC_bilateral_mean", "class median; 84 of 113 endpoints",
    "ED1b", "DESCRIPTIVE"),
  S("S2-19", R2, "nine control-only contrasts (five neuropil, four neuronal soma) against seven signatures",
    "external validation design",
    "9 contrasts x 7 signatures = 30 pairings; 0 microglia contrasts", "count",
    file.path(SD, "extended_data/v9_ed_external_full_source_data.csv"),
    "contrast / signature", "all rows", "F2g/ED2b", "EXTERNAL_VALIDATION"),
  S("S2-20", R2, "all ten expected pairings recovered in the expected direction and passed",
    "expected pairings supported", "10 of 10", "pairings",
    file.path(SD, "extended_data/v9_ed_external_full_source_data.csv"),
    "pairing_class / p_adjust", "pairing_class == expected", "F2g",
    "EXTERNAL_VALIDATION"),
  S("S2-21", R2, "normalised enrichment score 1.95-3.69 for positive-direction pairings",
    "expected-pairing NES range", "1.9524 to 3.6897 (one negative: -1.9183)",
    "NES", file.path(SD, "extended_data/v9_ed_external_full_source_data.csv"),
    "NES", "pairing_class == expected", "F2g", "EXTERNAL_VALIDATION"),
  # ---------------------------------------------------------------- Results 3
  S("S3-01", R3, "37 proteins reached FDR support for the SUS-RES contrast",
    "FDR-supported SUS-RES proteins", "37", "proteins",
    file.path(SD, "figure_03/v9_dap_track_source_data.csv"), "canonical count",
    "sum across 18 spatial units", "F3a", "DIRECT_INFERENCE"),
  S("S3-02", R3, "12 of the 18 units contained none at all",
    "spatial units with zero supported proteins", "12 of 18", "units",
    file.path(SD, "figure_03/v9_dap_track_source_data.csv"), "canonical count",
    "count == 0", "F3a", "DESCRIPTIVE"),
  S("S3-03", R3, "Twenty-eight of the 37 were in CA2 stratum lacunosum-moleculare",
    "CA2-SLM share", "28 of 37", "proteins",
    file.path(SD, "figure_03/v9_dap_track_source_data.csv"), "canonical count",
    "spatial_unit == CA2_slm", "F3a", "DESCRIPTIVE"),
  S("S3-04", R3, "highest pre-imputation missingness of the ten neuropil units (6.2-24.8%)",
    "CA2-SLM missingness range", "0.0617 to 0.2483", "fraction",
    file.path(SD, "extended_data/v9_ed_ca2_missing_source_data.csv"),
    "missing_fraction", "18 CA2-SLM acquisitions", "ED3b", "LIMITATION"),
  S("S3-05", R3, "systematic normalisation displacement (-0.146 SUS relative to RES)",
    "global normalisation displacement", "-0.14562", "log2",
    file.path(TB, "11_spatial_systems/ca2_slm_robustness"),
    "displacement", "SUS minus RES", "ED3c", "LIMITATION"),
  S("S3-06", R3, "displacement tracked missingness almost exactly (Pearson r = 0.93)",
    "missingness vs displacement", "0.931", "Pearson r",
    file.path(SD, "extended_data/v9_ed_ca2_displacement_source_data.csv"),
    "missing_fraction vs displacement", "across acquisitions", "ED3c",
    "LIMITATION"),
  S("S3-07", R3, "6 of the 28 CA2-SLM proteins qualified", "CA2-SLM qualified",
    "6 of 28", "proteins",
    file.path(TB, "11_spatial_systems/ca2_slm_robustness"), "robustness class",
    "qualified", "F3a/ED3", "DIRECT_INFERENCE"),
  S("S3-08", R3, "the 9 FDR-supported proteins outside CA2-SLM enter unchanged",
    "supported proteins outside CA2-SLM", "9", "proteins",
    file.path(SD, "figure_03/v9_dap_track_source_data.csv"), "canonical count",
    "spatial_unit != CA2_slm", "F3a", "DESCRIPTIVE"),
  S("S3-09", R3, "giving 15 robustness-qualified proteins in total",
    "robustness-qualified total", "15", "proteins",
    file.path(SD, "figure_03/v9_dap_track_source_data.csv"),
    "robustness-qualified count", "sum across 18 units", "F3a",
    "DIRECT_INFERENCE"),
  S("S3-10", R3, "seven ontology-defined program families (253 constituent GO terms)",
    "atlas size", "7 themes; 253 GO-BP terms", "count",
    "config/manuscript_go_theme_registry.tsv", "theme_id",
    "theme_role == primary; registry manuscript_go_themes_v3", "F3b",
    "DESCRIPTIVE"),
  S("S3-11", R3, "132 of 378 theme x unit x contrast cells contain a supported term",
    "atlas cells with support marker", "132 of 378 (34.9%)", "cells",
    file.path(SD, "figure_03/v9_atlas_source_data.csv"), "support marker",
    "7 themes x 18 units x 3 contrasts", "F3b/ED6", "DESCRIPTIVE"),
  S("S3-12", R3, "26.7% of FDR-supported GO occurrences and 14.0% of unique identifiers",
    "atlas coverage of supported GO", "953/3566 = 26.7%; 148/1056 = 14.0%",
    "fraction", file.path(SD, "figure_03/v9_atlas_source_data.csv"),
    "occurrence / unique GO_ID", "atlas vs all supported", "F3b",
    "DESCRIPTIVE"),
  S("S3-13", R3, "synaptic-signalling program in CA3-SR, SUS-RES and SUS-CON",
    "GO:0099536 NES / FDR",
    "SUS-RES -1.7192 / 4.12e-08; SUS-CON -1.7162 / 7.38e-06", "NES / FDR",
    file.path(SD, "figure_03/v9_bridge_source_data.csv"), "NES / GSEA_FDR",
    "GO:0099536, CA3_sr neuropil", "F3c,d", "DIRECT_INFERENCE"),
  S("S3-14", R3, "no support for the resilient-versus-control arm (FDR 0.19)",
    "GO:0099536 RES-CON", "NES +1.3424; FDR 0.1881", "NES / FDR",
    file.path(SD, "figure_03/v9_bridge_source_data.csv"), "NES / GSEA_FDR",
    "GO:0099536, CA3_sr, RES-CON", "F3c,d", "LIMITATION"),
  S("S3-15", R3, "mRNA-processing program in CA2 neuronal soma",
    "GO:0006397 NES / FDR",
    "SUS-RES +2.1258 / 1.93e-07; SUS-CON +1.6201 / 0.0284; RES-CON -1.1701 / 0.7764",
    "NES / FDR", file.path(SD, "figure_03/v9_bridge_source_data.csv"),
    "NES / GSEA_FDR", "GO:0006397, CA2 neuronal soma", "F3c,e",
    "DIRECT_INFERENCE"),
  S("S3-16", R3, "oxidative-phosphorylation program supported in all three contrasts",
    "GO:0006119 NES / FDR",
    "SUS-RES -2.1110 / 5.75e-05; SUS-CON -2.7608 / 1.52e-08; RES-CON -1.7751 / 3.15e-03",
    "NES / FDR", file.path(SD, "figure_03/v9_bridge_source_data.csv"),
    "NES / GSEA_FDR", "GO:0006119, CA1 microglia-enriched ROI", "F3c,f",
    "DIRECT_INFERENCE"),
  S("S3-17", R3, "median per-comparison Spearman rho = 0.93",
    "GSEA-CAMERA rank agreement", "0.9292 (range 0.8236-0.9611)", "Spearman rho",
    file.path(TB, "10_biological_integration"), "spearman", "54 comparisons",
    "n/a (sensitivity)", "SENSITIVITY"),
  S("S3-18", R3, "all 3,559 FDR-supported terms direction-concordant; 22.1% retain FDR",
    "CAMERA concordance", "3559 terms; 100% concordant; 22.11% retained",
    "percent", file.path(TB, "10_biological_integration"),
    "direction / CAMERA FDR", "GSEA FDR-supported terms", "n/a", "SENSITIVITY"),
  S("S3-19", R3, "no module-outcome contrast survived correction (0 of 45; smallest FDR 0.25)",
    "WGCNA module-phenotype", "0 of 45; smallest FDR 0.2450", "tests",
    file.path(TB, "06_modules_WGCNA/group_effects"), "FDR",
    "module x contrast cells", "ED WGCNA b", "LIMITATION"),
  S("S3-20", R3, "no stress x spatial-unit interaction omnibus test FDR-supported (0 of 35; smallest FDR 0.27)",
    "WGCNA interaction omnibus", "0 of 35; smallest FDR 0.2741", "tests",
    file.path(TB, "06_modules_WGCNA/group_effects"), "FDR",
    "interaction_omnibus family", "ED WGCNA b", "LIMITATION"),
  S("S3-21", R3, "exact permutation P = 0.58, 0.80 and 0.74; attainable floor 0.004",
    "whole-network group comparison",
    "0.5786 / 0.8036 / 0.7357; floor 0.003571", "P",
    file.path(TB, "11_spatial_systems"), "exact permutation p",
    "neuropil / soma / microglia", "ED8b,c", "LIMITATION"),
  S("S3-22", R3, "no edge-behaviour association survived correction (0 of 48)",
    "edge-behaviour coupling", "0 of 48; smallest BH 0.4283", "tests",
    file.path(TB, "08_behavior_physio_coupling"), "BH p",
    "48 distinct edge x outcome tests", "ED8d", "LIMITATION"),
  S("S3-23", R3, "none of the 63 displayed values is individually FDR-supported (smallest BH FDR 0.53)",
    "leading-edge protein FDR", "0 of 63; smallest BH 0.5251", "proteins",
    file.path(SD, "figure_03/v9_prot_syn_source_data.csv"), "fdr / sig",
    "21 proteins x 3 contrasts across panels g,h,i", "F3g-i", "LIMITATION"))

utils::write.csv(prov, file.path(MS, "results_statement_provenance.csv"),
                 row.names = FALSE)

# ------------------------------------------------------------- Methods TODO
T <- function(id, sid, topic, src, prio, notes)
  data.frame(todo_id = id, results_statement_id = sid, method_topic = topic,
             authoritative_source = src, priority = prio, notes = notes,
             stringsAsFactors = FALSE)
todo <- rbind(
  T("MT-01", "S2-01..S2-05", "LCM and DIA-MS acquisition; identification depth",
    "docs/DATASETS.md; 03_qc_exploration/00_dataset_qc_report.r", "high",
    "state the 70% missingness filter and that depth is per acquisition, not per animal"),
  T("MT-02", "S2-01", "bilateral animal-level aggregation contract",
    "manuscript_methods_contract.csv row preprocessing_bilateral", "high",
    "the biological replicate is the animal; hemispheres are repeated tissue"),
  T("MT-03", "S2-19..S2-21", "external signature validation design",
    "04_differential_expression_enrichment/09_control_spatial_identity_validation.r",
    "high", "name the external reference and the three BH families actually used"),
  T("MT-04", "S2-19..S2-21", "PH-009: p_adjust column semantics",
    "results/source_data/.../v9_ed_external_full_source_data.csv", "high",
    "the column named p_adjust equals the raw single-set p; Methods must not call it adjusted"),
  T("MT-05", "S3-04..S3-09", "CA2-SLM robustness criteria",
    "11_spatial_systems/16_ca2_slm_robustness_audit.R", "high",
    "prespecified thresholds; robustness-qualified = not excluded, not a second test"),
  T("MT-06", "S3-10..S3-12", "canonical GSEA contract",
    "manuscript_methods_contract.csv row gsea", "high",
    "moderated t, median per symbol, gseGO GO-BP, BH within comparison, eps = 1e-10"),
  T("MT-07", "S3-10..S3-12", "atlas construction and the descriptive aggregation rule",
    "docs/ATLAS_PROGRAM_SELECTION_AND_NAMING_RULES.md", "high",
    "anchor-based registry v3; median NES; no theme-level FDR family"),
  T("MT-08", "S3-13..S3-16", "exemplar selection rule",
    "final_truth_v9 audit f3_program_example tables", "high",
    "one illustrative example per compartment, editorially chosen after contrasts were known"),
  T("MT-09", "S3-13..S3-16", "eps = 1e-10 floor disclosure",
    "final_figure_legends_v9.md", "high",
    "report the current count of floored occurrences, not the legend's stale figure"),
  T("MT-10", "S3-17..S3-18", "CAMERA sensitivity design",
    "manuscript_methods_contract.csv row camera_sensitivity", "medium",
    "cameraPR preranked, inter.gene.cor 0.01; sensitivity, never validation"),
  T("MT-11", "S3-19..S3-20", "WGCNA model and families",
    "manuscript_methods_contract.csv row wgcna", "medium",
    "lmerTest eigengene ~ StressGroup + SpatialUnit + (1|AnimalID)"),
  T("MT-12", "S3-21..S3-23", "network permutation and edge-behaviour tests",
    "manuscript_methods_contract.csv rows network, behaviour_correlation",
    "medium",
    "exact label enumeration; state the attainable p floor; 8 neuropil edges only"),
  T("MT-13", "S2-13..S2-17b", "bilateral contrast registry and the DG mirror",
    "R/control_spatial_identity_utils.R; bilateral_spatial_identity_summary.csv",
    "high",
    "11 contrasts are manuscript-locked (7 neuropil + 4 soma); the 4 microglia contrasts are regional context; DG_MO and DG_PO are algebraic mirror images and must not be counted as two independent laminar contrasts"))
utils::write.csv(todo, file.path(MS, "methods_todo.csv"), row.names = FALSE)

# ---------------------------------------------------------- claim provenance
C <- function(id, sec, para, text, class, prim, sec2, stat, panel, allow, prohib,
              status)
  data.frame(claim_id = id, section = sec, paragraph = para, claim_text = text,
             claim_class = class, primary_source = prim, secondary_source = sec2,
             statistical_support = stat, figure_panel = panel,
             allowed_wording = allow, prohibited_wording = prohib,
             verification_status = status, stringsAsFactors = FALSE)
claims <- rbind(
  C("C2-1", R2, 1, "The workflow yielded 323 acquisitions across three compartments at the stated depth",
    "DESCRIPTIVE", "v9_depth_source_data.csv", "qc_summary_by_celltype_layer.csv",
    "none - descriptive", "F2a,b", "yielded; median depth",
    "acquisitions as biological replicates", "VERIFIED"),
  C("C2-2", R2, 2, "Compartment, not stress group, dominates global structure",
    "DESCRIPTIVE", "v9_pca_source_data.csv", "joint compartment QC audit",
    "variance decomposition only; no test (F2c declared descriptive)", "F2c",
    "accounted for; descriptive variance decomposition",
    "P values; establishes; proves", "REVISED_AFTER_RED_TEAM"),
  C("C2-3", R2, 3, "Control animals show a coherent anatomical fingerprint",
    "DESCRIPTIVE", "v9_fingerprint_source_data.csv",
    "v9_compartment_source_data.csv", "none - descriptive; rows rank-selected from the displayed contrasts",
    "F2d,e", "defines a coherent fingerprint; most abundant in expected compartment",
    "reproducible (not shown by this panel); compartment-restricted",
    "REVISED_AFTER_RED_TEAM"),
  C("C2-4", R2, 4, "Bilateral concordance varies more by compartment than by anatomical scale",
    "DESCRIPTIVE", "bilateral_spatial_identity_summary.csv",
    "v9_ed_precision_source_data.csv", "none - descriptive; no test applied",
    "F2f, ED1a,b", "varies by compartment; median and range per compartment",
    "specific to CA1; depends on anatomical scale; least reproducible in the dataset",
    "REVISED_AFTER_RED_TEAM"),
  C("C2-5", R2, 5, "Neuropil and soma assignments recover published hippocampal anatomy",
    "EXTERNAL_VALIDATION", "v9_ed_external_full_source_data.csv",
    "control_spatial_identity_validation", "10 of 10 expected pairings supported under the stored signature-family correction",
    "F2g, ED2b", "external validation; recovered in the expected direction",
    "specificity; validated generally; microglia included", "VERIFIED"),
  C("C3-1", R3, 1, "Individual-protein differences are sparse",
    "DIRECT_INFERENCE", "v9_dap_track_source_data.csv", "known_issues_v9.md",
    "BH within the DA family; 37 supported, 12 of 18 units with none", "F3a",
    "sparse; reached FDR support", "widespread; no effect in 12 units",
    "VERIFIED"),
  C("C3-2", R3, 2, "The CA2-SLM concentration weakens under QC qualification",
    "LIMITATION", "CA2_SLM_DAP_robustness tables",
    "v9_ed_ca2_missing / displacement source data",
    "prespecified robustness criteria; 6 of 28 qualified", "F3a, ED3",
    "weakens substantially; qualified rather than headline",
    "does not survive; hotspot; artefact proven", "REVISED_AFTER_RED_TEAM"),
  C("C3-3", R3, 3, "Coordinated program-level differences are detectable",
    "DESCRIPTIVE", "v9_atlas_source_data.csv",
    "ontology_aware_gsea_theme_assignments_all_contrasts.csv",
    "descriptive median NES aggregation; NO theme-level FDR family", "F3b, ED6",
    "detectable; supported constituent terms occur in 132 of 378 cells",
    "nevertheless; program families differ across spatial contexts; theme significance",
    "REVISED_AFTER_RED_TEAM"),
  C("C3-4", R3, 4, "Two exemplars are susceptibility-associated; one is graded and stress-associated",
    "DIRECT_INFERENCE", "v9_bridge_source_data.csv",
    "f3_program_example_selection.csv",
    "BH over GO-BP within each comparison; RES-CON arms unsupported for two exemplars",
    "F3c-f", "susceptibility-associated; graded stress-associated direction",
    "divergent; susceptibility-specific; trajectory; cell-intrinsic", "VERIFIED"),
  C("C3-5", R3, 5, "Sensitivity, module and network layers bound the program-level reading",
    "SENSITIVITY", "CAMERA concordance tables", "WGCNA and network tables",
    "CAMERA 22.1% retained; WGCNA 0 of 45 and 0 of 35; network exact P 0.58-0.80; edges 0 of 48",
    "ED6, ED WGCNA, ED8", "sensitivity analysis; did not survive correction; not detectable at three animals per group",
    "validation; replication; confirmed; no effect; unchanged", "REVISED_AFTER_RED_TEAM"),
  C("C3-6", R3, 6, "Neither evidence level is claimed to be the stronger",
    "LIMITATION", "core_story_corrected.md", "claim_chain_audit.md",
    "separate BH families, never placed on a common scale", "F3a,b",
    "assessed in separate multiple-testing families",
    "stronger; richer; but", "VERIFIED"))
utils::write.csv(claims, file.path(MS, "results_claim_provenance.csv"),
                 row.names = FALSE)

# ------------------------------------------------------- red-team review log
#
# Seven independent reviewers checked the draft against the claim contract, one
# per checklist dimension, quoting sentences verbatim. Each material finding is
# recorded with its disposition. "Sentence checked" counts are the reviewers'
# own; the dispositions below are the author's adjudication.
RT <- function(id, q, sentence, verdict, action, evidence)
  data.frame(review_id = id, checklist_question = q, sentence = sentence,
             verdict = verdict, action_taken = action, evidence = evidence,
             stringsAsFactors = FALSE)
rt <- rbind(
  RT("RT-01", "Q9 specificity / Q1 verb licensing / Q4 contrast / numbers",
     "The lower tail is specific to CA1: ... the three CA1 strata contrasts were the least reproducible in the dataset",
     "REAL DEFECT - flagged BLOCKER by four independent reviewers",
     "SENTENCE REMOVED AND PARAGRAPH REWRITTEN",
     "Re-derived from bilateral_spatial_identity_summary.csv: CA1-SLM r = 0.7383 ranks 8th of 15, at the inventory median; four non-CA1 contrasts fall below it (microglia CA2 0.4951, CA1 0.5381, CA3 0.5793; neuropil CA1_SO_vs_CA3_SO 0.5812). Claim was false AND used a reserved word."),
  RT("RT-02", "Q3 data vs interpretation / Q2 biological n",
     "compartment accounted for essentially all of the variance along PC1 (eta2 = 0.96, P = 1.2e-217) ... (eta2 = 8.5e-05, P = 0.99)",
     "REAL DEFECT - flagged BLOCKER by three independent reviewers",
     "BOTH P VALUES REMOVED; eta-squared retained with an explicit descriptive statement",
     "F2c legend: 'Descriptive; no hypothesis test is performed in this panel.' The P values' degrees of freedom come from 323 acquisitions, which the preceding paragraph declares are not independent replicates."),
  RT("RT-03", "Q1 verb licensing",
     "it establishes that the outcome-associated differences examined later are small relative to compartment identity",
     "REAL DEFECT - 'establishes' exceeds the claim-verb registry, and the clause is a cross-family magnitude comparison",
     "CLAUSE DELETED", "claim_verb_registry.csv; the PCA is acquisition-level while the later contrasts are animal-level within spatial unit."),
  RT("RT-04", "Q1 verb licensing / Q3 data vs interpretation",
     "Coordinated differences ... are nevertheless present",
     "REAL DEFECT - 'nevertheless' is the adversative PH-002 removed at source",
     "CHANGED TO 'are detectable'",
     "PH-002: 'the adversative carries the ranking that the conjunction does not'. I had reintroduced the construction I removed earlier in this project."),
  RT("RT-05", "Q9 specificity (inverse error)",
     "Program families differ across spatial contexts and across the three contrasts",
     "REAL DEFECT - a spatial-heterogeneity assertion made without using a banned word",
     "REWRITTEN as a factual count with 'no test of that unevenness was performed'",
     "The only heterogeneity test is the WGCNA omnibus, 0 of 35 FDR-supported."),
  RT("RT-06", "Q1 verb licensing / Q4 dataset wording",
     "ten prespecified compartment markers showed the expected compartment-restricted abundance patterns",
     "REAL DEFECT - 'restricted' is reserved under contract section 6 and the panel is declared untested",
     "CHANGED TO 'were most abundant in their expected compartment'",
     "Contract section 6; F2e legend declares the panel descriptive."),
  RT("RT-07", "Q3 data vs interpretation",
     "Within control animals, the proteome carries a reproducible anatomical fingerprint",
     "REAL DEFECT - reproducibility is shown by F2f/ED1a, not by F2d/F2e, and F2d rows are rank-selected from the contrasts displayed",
     "CHANGED TO 'defines a coherent anatomical fingerprint' plus an explicit circularity disclosure",
     "claim_chain_audit: 'Selected from the same anatomical contrasts the panel displays.'"),
  RT("RT-08", "Q6 null overstated (over-negation)",
     "That apparent concentration does not survive quality-control scrutiny",
     "REAL DEFECT - over-negation; 6 of 28 did qualify and CA2-SLM still contributes 6 of the 15 robustness-qualified proteins",
     "CHANGED TO 'weakens substantially ... from 28 proteins to 6'",
     "CA2_SLM_DAP_robustness tables."),
  RT("RT-09", "Q2 biological n / Q3 data vs interpretation",
     "Six GSEA FDR values down to 1.5e-08 reported with none of the standing caveats",
     "REAL DEFECT - every enrichment legend in the frozen package attaches the ranking-conditional and eps-floor caveats",
     "ADDED one caveat sentence covering all three exemplars",
     "All three exemplars sit at the eps = 1e-10 floor in at least one displayed cell."),
  RT("RT-10", "Q4 contrast correctness",
     "all three representative terms reproducing their direction without retaining it",
     "REAL DEFECT - true only for the susceptible-versus-resilient arm",
     "SCOPED to the SUS-RES arm, with the three CAMERA FDRs given",
     "CAMERA classification is per contrast arm, not per term."),
  RT("RT-11", "Q4 dataset wording / Q6 null scope",
     "no edge-behaviour association survived correction (0 of 48)",
     "REAL DEFECT - reads as a survey of the whole spatial network; it covers 8 neuropil pairs only",
     "SCOPED to 'the eight neuropil spatial-unit pairs tested', with the untested compartments named",
     "Edge-behaviour coupling covers 8 neuropil spatial-unit pairs."),
  RT("RT-12", "Q4 dataset wording",
     "the spatial assignments recover independently published hippocampal anatomy",
     "REAL DEFECT - reads as all three compartments; zero microglia contrasts enter F2g/ED2b",
     "SCOPED to 'the neuropil and neuronal-soma spatial assignments', with the microglia gap stated",
     "v9_ed_external_full_source_data.csv: 5 neuropil + 4 soma contrasts, 0 microglia."),
  RT("RT-13", "numbers",
     "the three analysis matrices comprised 5,054, 5,538 and 5,229 protein groups (union 5,694)",
     "REAL DEFECT - the union figure could not be re-derived; the joint-QC audit gives 5,621",
     "UNION COUNT REMOVED; 'quantified' changed to 'detected'",
     "No source file yields 5,694."),
  RT("RT-14", "numbers / Q4 dataset wording",
     "across 15 prespecified contrasts",
     "REAL DEFECT - only 11 of the 15 are manuscript-locked; the 4 microglia contrasts are regional context, and DG_MO/DG_PO are algebraic mirror images",
     "REWRITTEN; the locked/context split is now in provenance S2-13 and Methods TODO MT-13",
     "manuscript_locked column: TRUE = 11, FALSE = 4. DG rows identical to 7 dp."),
  RT("RT-15", "Q1 verb licensing / Q2 biological n",
     "Together these results establish that the workflow resolves reproducible hippocampal molecular organisation",
     "REAL DEFECT - 'establish' exceeds the registry; 'reproducible' unqualified means between hemispheres of the SAME animal",
     "REWRITTEN as 'show ... reproducible between the two hemispheres of the same animal - internal consistency rather than independent replication'",
     "Bilateral design is 3 CON animals, both hemispheres."),
  RT("RT-16", "Q7 sensitivity as validation", "CAMERA description throughout",
     "CLEAN - no change needed",
     "NONE",
     "Reviewer confirmed CAMERA is never called validation, replication or confirmation, and the disclaimer sits in the same sentence."),
  RT("RT-17", "Q8 leading-edge significance", "Fig. 3g-i description",
     "CLEAN - no change needed", "NONE",
     "0 of 63 displayed values individually FDR-supported; smallest BH 0.53 stated in the same sentence."),
  RT("RT-18", "Q5 cell-context wording", "All microglia and soma mentions",
     "CLEAN - no change needed", "NONE",
     "Reviewer grep: every mention is 'microglia-enriched ROI' or 'microglia-enriched compartment'; no 'microglial proteome', 'microglia-specific', 'cell-intrinsic' or 'cell-autonomous' anywhere; soma never given laminar resolution."))
utils::write.csv(rt, file.path(MS, "results_red_team_review.csv"),
                 row.names = FALSE)

cat("results_statement_provenance.csv rows:", nrow(prov), "\n")
print(table(prov$manuscript_section, prov$claim_type))
cat("\nresults_claim_provenance.csv rows:", nrow(claims), "\n")
print(table(claims$claim_class))
cat("\nresults_red_team_review.csv rows:", nrow(rt), "\n")
print(table(sub(" .*", "", rt$verdict)))
cat("\nmethods_todo.csv rows:", nrow(todo), "\n")
