#!/usr/bin/env Rscript

# Part-26: a README in every final_truth_v9 output folder.
#
# The folders are otherwise a wall of similarly named files, and the only
# description of what any of them is lives in the contract. These READMEs are
# GENERATED from that contract on every build, so they cannot drift away from
# what the scripts actually write. Nothing here is hand-maintained.

source(file.path("R", "paths.R"))
source(repo_path("R", "integration_utils.R"))
source(repo_path("R", "nature_v2_figure_utils.R"))
source(repo_path("R", "final_truth_v9_figure_utils.R"))
Sys.setenv(PROTEOMICS_SCRIPT_ID = "figures/final_truth_v9_readmes.R")

args <- commandArgs(trailingOnly = TRUE)
if ("--dry-run" %in% args || is_dry_run()) {
  message("[DRY-RUN] final_truth_v9 folder READMEs")
  quit(save = "no", status = 0L)
}

ct <- s9f_contract()
FIGKEYS <- unique(vapply(ct$figures, function(f) as.character(f$figure_key),
                         character(1)))
panel_of <- function(id)
  Filter(function(p) identical(as.character(p$id), id), ct$panels)[[1]]

HDR <- function(title) c(
  paste0("# ", title), "",
  paste0("**", ct$status, "** — contract `", ct$contract_version, "`."),
  "",
  paste0("This is a CANDIDATE figure layer. It is not the manuscript. ",
         "Canonical outputs and every earlier candidate layer are untouched ",
         "by the scripts that write here, and nothing in this folder is ",
         "promoted by running them."),
  "")

FOOT <- function(scripts) c(
  "", "## Regenerating", "",
  "From the repository root:", "", "```",
  paste0("Rscript ", scripts), "```", "",
  paste0("Every file in this folder is overwritten on each run and is ",
         "byte-reproducible: two consecutive builds produce identical ",
         "artefacts. Do not edit anything here by hand — edit the ",
         "renderer or the contract instead."),
  "",
  paste0("_Generated by `figures/final_truth_v9_readmes.R` from ",
         "`figures/figure_final_truth_v9_contract.yml`. Do not edit._"))

written <- character(0)
put <- function(dir, lines) {
  if (!dir.exists(dir)) return(invisible(NULL))
  writeLines(lines, file.path(dir, "README.md"))
  written <<- c(written, relative_to(file.path(dir, "README.md")))
}

# ------------------------------------------------------------- figure dirs
for (k in FIGKEYS) {
  figs <- Filter(function(f) identical(as.character(f$figure_key), k),
                 ct$figures)
  ids <- unique(unlist(lapply(figs, function(f)
    vapply(f$layout, function(it) as.character(it$panel), character(1)))))
  scr <- paste0("figures/final_truth_v9_", k, ".R")

  tab <- c("| Figure | Panel | Renderer | Size (mm) | What it shows |",
           "|---|---|---|---|---|")
  for (f in figs) for (it in f$layout) {
    p <- panel_of(as.character(it$panel))
    nar <- gsub("[\r\n]+", " ", as.character(p$narrative %||% p$role %||% ""))
    tab <- c(tab, sprintf("| %s | %s | `%s` | %g × %g | %s |",
                          as.character(f$name), as.character(it$label),
                          as.character(p$renderer), as.numeric(it$w),
                          as.numeric(it$h), nar))
  }

  put(path_results("figures", "manuscript_candidates", "final_truth_v9", k,
                   "assembled"),
      c(HDR(paste0("Assembled figures — ", k)),
        paste0("One SVG and one PDF per figure, composed at the final print ",
               "size of 183 mm wide. The PDF is written directly on a cairo ",
               "device, so it is genuine vector: embedded subset fonts and ",
               "real text-showing operators, with no page-sized raster. ",
               "Judge print quality from these files, not from a raster ",
               "preview."),
        "", "## Figures here", "",
        paste0("- `", vapply(figs, function(f) as.character(f$name),
                             character(1)), ".svg` / `.pdf` — ",
               vapply(figs, function(f) as.character(f$question %||% ""),
                      character(1))),
        "", "## Panels", "", tab, FOOT(scr)))

  put(path_results("figures", "manuscript_candidates", "final_truth_v9", k,
                   "panels"),
      c(HDR(paste0("Individual panels — ", k)),
        paste0("One SVG per panel at the exact millimetre box the contract ",
               "assigns it. These are the components the assembled figure is ",
               "built from; they are written for inspection and are not ",
               "separately submitted."),
        "", "## Panels", "", tab, FOOT(scr)))

  put(file.path(path_results("source_data", "manuscript_candidates",
                             "final_truth_v9"), k),
      c(HDR(paste0("Panel source data — ", k)),
        paste0("One CSV per panel holding exactly the numbers that panel ",
               "draws, so any panel can be reproduced or re-plotted without ",
               "rerunning the pipeline. These files are MACHINE-oriented: ",
               "abbreviated headers, and a provenance column repeated on ",
               "every row."),
        "",
        paste0("For reader-facing statistics with full column names, units, ",
               "the n each statistic rests on and its multiple-testing ",
               "family, use the Supplementary Tables in ",
               "`results/tables/manuscript_candidates/final_truth_v9/",
               "supplementary/` instead."),
        "", "## Files", "",
        paste0("- `", sort(ids), "_source_data.csv`"), FOOT(scr)))
}

# -------------------------------------------------------------- table dirs
put(path_results("tables", "manuscript_candidates", "final_truth_v9"),
    c(HDR("Audit tables"),
      "| File | Contents |", "|---|---|",
      "| `vector_export_audit.csv` | Per figure: embedded font count, text-showing operators, largest raster object, and whether a page-sized raster is present. A page-sized raster is a hard build failure. |",
      "| `preview_render_index.csv` | Where the 300 dpi and 900 dpi previews were written, and their pixel dimensions. |",
      "| `supplementary/` | Reader-facing statistics tables and their data dictionary. |",
      FOOT(c("figures/final_truth_v9_vector_audit.R",
             "figures/final_truth_v9_previews.R"))))

sup <- path_results("tables", "manuscript_candidates", "final_truth_v9",
                    "supplementary")
dd_path <- file.path(sup, "ST0_data_dictionary.csv")
sup_tab <- c("| Table | Contents |", "|---|---|")
if (file.exists(dd_path)) {
  dd <- nv_read_csv(dd_path)
  u <- unique(dd[, c("table_file", "table_title")])
  sup_tab <- c(sup_tab, sprintf("| `%s` | %s |", u$table_file, u$table_title))
}
put(sup, c(HDR("Supplementary statistics tables"),
           paste0("Publication-facing tables derived from the panel source ",
                  "data. Nothing is recomputed and no test is run here: every ",
                  "value is a read of a stored result. Each table states the ",
                  "test that produced its statistic, the multiple-testing ",
                  "family it was corrected in, and the number of biological ",
                  "replicates it rests on — 9 animals, 3 per group. Where ",
                  "a quantity is descriptive and carries no test, the table ",
                  "says so rather than leaving the column blank."),
           "", "## Tables", "", sup_tab, "",
           paste0("`ST0_data_dictionary.csv` defines every column of every ",
                  "table above and carries the per-table interpretation note."),
           FOOT("figures/final_truth_v9_supplementary_tables.R")))

# ------------------------------------------------------- reports & previews
put(path_results("reports", "manuscript_candidates", "final_truth_v9"),
    c(HDR("Build reports"),
      "| File | Contents |", "|---|---|",
      "| `<figure_key>/final_truth_v9_qa.csv` | Hard QA gate result. The build fails if any text falls below 5 pt, if panels overlap or overflow the page, or if a renderer errors. |",
      "| `<figure_key>/final_truth_v9_panel_status.csv` | Per-panel render status and the box it was drawn into. |",
      "| `<figure_key>/final_truth_v9_variant_status.csv` | Per-figure assembly status. |",
      "| `final_figure_story_v8.md` | What the finished figures establish, in prose, and the conclusion they do and do not support. |",
      FOOT(c("figures/final_truth_v9_figure_02.R",
             "figures/final_truth_v9_figure_03.R",
             "figures/final_truth_v9_extended_data.R"))))

put(path_results("figures", "manuscript_candidates", "final_truth_v9",
                 "previews"),
    c(HDR("Raster previews"),
      paste0("Review aids only — the delivered artwork is the SVG and the ",
             "cairo PDF in each figure's `assembled/` folder."),
      "",
      paste0("Both densities are deliberate. A 300 dpi raster softens 5 pt ",
             "type enough to look illegible when it is not, and an earlier ",
             "audit nearly mis-reported that rasterisation artefact as a ",
             "print defect. The 900 dpi pass settles legibility questions; ",
             "the 300 dpi pass is what a referee sees on screen."),
      "", "| Item | Contents |", "|---|---|",
      "| `300dpi/` | One PNG per assembled figure at 300 dpi. |",
      "| `900dpi/` | One PNG per assembled figure at 900 dpi. |",
      "| `final_truth_v9_contact_sheet.png` | All figures on one sheet; the only view in which main/Extended Data balance is visible at a glance. |",
      FOOT("figures/final_truth_v9_previews.R")))


# ------------------------------------------------------- known issues (S26/S28)
ki <- c(
"# Known issues and interpretation notes - final_truth_v9",
"",
"Generated from the contract. Candidate layer; not promoted.",
"",
"## Upstream: ExpGroup is typed numeric in variance partitioning",
"",
paste0("In `results/tables/03_qc_exploration/06_variance_partitioning/` the ",
       "term `ExpGroup` is stored with `class = numeric` and example values ",
       "`2; 3; 1`, while every other categorical term - Region, Layer, ",
       "ReplicateGroup, AnimalID - is coerced to a factor. A numeric stress ",
       "group enters that model as a continuous covariate with one degree of ",
       "freedom and imposes an arbitrary linear CON -> RES -> SUS ordering, so ",
       "the group variance it reports is not a valid categorical stress-group ",
       "variance estimate."),
"",
paste0("**Status.** The stage is excluded from every displayed figure and its ",
       "group-variance value is not cited anywhere in the figures, legends or ",
       "statistics tables. A dependency guard in the test suite fails if any ",
       "manuscript panel is ever wired to it. It is NOT repaired here, because ",
       "repairing it would mean rerunning an analysis stage; it should be fixed ",
       "separately for repository correctness."),
"",
"## Panels that are characterisation, not validation",
"",
paste0("Figure 2g tests internal anatomical contrasts against independently ",
       "published hippocampal signatures and is genuine EXTERNAL validation. ",
       "Figure 2h annotates the SAME proteomic data with canonical gene-set ",
       "programs: it is functional characterisation and is not independent ",
       "validation. ED2 carries the complete inventory of both."),
"",
"## Theme-level enrichment is a descriptive aggregation",
"",
paste0("In the Figure-3 and ED6 theme atlases, colour is the median NES of ",
       "mapped canonical GO terms and is descriptive. A support marker means ",
       "at least one constituent GO term passed its own prespecified FDR ",
       "threshold. The theme cell has no FDR family of its own and no ",
       "theme-level p-value or FDR is computed or implied."),
"",
"## Selected leading-edge proteins are not independent evidence",
"",
paste0("Figure 3 g/h/i show leading-edge constituents of the enrichment result ",
       "directly above them, selected by the prespecified stored ",
       "rank-statistic rule. They are not an independent validation of the ",
       "enrichment, not individually FDR-supported proteins - the smallest BH ",
       "FDR among them is 0.53 - and not an unbiased protein sample."),
"",
"## Pairwise contrasts are algebraically related",
"",
paste0("SUS-RES equals SUS-CON minus RES-CON to machine precision wherever all ",
       "three are displayed. They are shown jointly to make the three-group ",
       "trajectory legible and must not be read as three independent ",
       "replications."),
"",
"## Robustness-qualified is not a uniform second-stage test",
"",
paste0("Of the 37 FDR-supported SUS-RES proteins, the 28 in CA2-SLM underwent ",
       "the detailed missingness and QC qualification shown in ED3, of which 6 ",
       "qualified; the 9 outside CA2-SLM enter unchanged because they were ",
       "never at risk from that artefact. 'Robustness-qualified' therefore ",
       "means 'not excluded by the CA2-SLM missingness audit', not 'passed an ",
       "additional test'."),
"",
"## ED8b control reference",
"",
paste0("For each CON animal the network distance was computed to a ",
       "leave-one-CON-animal-out consensus, so no animal is compared with a ",
       "consensus containing itself; RES and SUS animals were compared with ",
       "the full CON consensus. This was verified against the edge data rather ",
       "than against its stored label; see ",
       "`results/tables/manuscript_candidates/final_truth_v9/",
       "ed8b_consensus_audit.csv`."),
"",
"_Generated by `figures/final_truth_v9_readmes.R`. Do not edit._")
kp <- file.path(path_results("reports", "manuscript_candidates", "final_truth_v9"),
                "known_issues_v9.md")
writeLines(ki, kp)
written <- c(written, relative_to(kp))
cat("\n===== FOLDER READMEs =====\n")
cat(paste0("  ", written), sep = "\n")
cat("\nwritten:", length(written), "\n")
