# Manual-adjudication support and canonical display-label resolution.
#
# WHAT THIS FILE IS FOR
#   1. One canonical resolver for the biological display label, so consumers
#      stop reinventing precedence and the same entity can never appear under
#      two names inside one artifact.
#   2. A hierarchy-redundancy detector, so a multi-module supermodule and its
#      members do not all carry the same name.
#   3. The final human-approval table, carrying the curated adjudication for
#      each entity with its evidence and an explicitly EMPTY human decision.
#
# NOTHING HERE ACTIVATES A LABEL. Activation requires a registry that is
# adjudication_status = "reviewed" AND names a real reviewer; the proposals
# generated by this pipeline can never satisfy that.

# `%||%` comes from the canonical R/null_coalescing.R, loaded via R/paths.R.

# The Stage 07 canonical lookup is named through the WGCNA path resolver. This
# file has no plain source() block of its own, so the guard is explicit.
if (!exists("wgcna_interpretable_artifact", mode = "function")) {
  if (!exists("repo_path", mode = "function")) {
    paths_file <- if (file.exists(file.path("R", "paths.R"))) file.path("R", "paths.R") else file.path("..", "R", "paths.R")
    source(paths_file)
  }
  source(repo_path("R", "wgcna_paths.R"))
}

wal_contract_version <- function() "wgcna_label_activation_v1"

# ------------------------------------------------- canonical label resolver

wal_label_sources <- function() {
  c("active_reviewed_registry", "stage07_canonical", "stage01_fallback",
    "entity_id_fallback")
}

# A registry is ACTIVE only when a human has adjudicated it and is named.
# This is deliberately stricter than the proposal contract.
wal_is_active_reviewed <- function(registry) {
  if (!is.data.frame(registry) || !nrow(registry)) return(FALSE)
  status <- if (is.null(registry$adjudication_status)) {
    rep(NA_character_, nrow(registry))
  } else tolower(trimws(as.character(registry$adjudication_status)))
  reviewer <- if (is.null(registry$reviewer)) rep(NA_character_, nrow(registry)) else
    trimws(as.character(registry$reviewer))
  label <- if (is.null(registry$reviewed_biological_label)) {
    rep(NA_character_, nrow(registry))
  } else trimws(as.character(registry$reviewed_biological_label))
  all(status %in% c("reviewed", "adjudicated", "active")) &&
    all(!is.na(reviewer) & nzchar(reviewer) & !tolower(reviewer) %in% c("na", "none")) &&
    all(!is.na(label) & nzchar(label))
}

# Resolve ONE biological display label per dataset + level + entity_id.
#
# Precedence:
#   1. an ACTIVE validated reviewed registry
#   2. the Stage-07 canonical / final automatic label
#   3. the Stage-01 ModuleLabel_Final, as a last resort
#   4. the entity id itself, so a label is never empty
#
# Historical labels are never discarded: they are returned alongside as
# provenance columns.
resolve_wgcna_display_label <- function(entities, reviewed = NULL,
                                        stage07 = NULL, stage01 = NULL) {
  if (!is.data.frame(entities)) {
    stop("entities must be a data frame.", call. = FALSE)
  }
  need <- c("dataset", "level", "entity_id")
  missing <- setdiff(need, names(entities))
  if (length(missing)) {
    stop("entities is missing required column(s): ",
         paste(missing, collapse = ", "), ".", call. = FALSE)
  }
  key <- function(d) paste(as.character(d$dataset), as.character(d$level),
                           as.character(d$entity_id), sep = "\r")
  k <- key(entities)

  lookup <- function(tbl, col) {
    out <- rep(NA_character_, length(k))
    if (is.null(tbl) || !nrow(tbl) || is.null(tbl[[col]])) return(out)
    tk <- key(tbl)
    idx <- match(k, tk)
    v <- trimws(as.character(tbl[[col]]))
    v[!nzchar(v)] <- NA_character_
    out[!is.na(idx)] <- v[idx[!is.na(idx)]]
    out
  }

  reviewed_active <- wal_is_active_reviewed(reviewed)
  reviewed_label <- if (reviewed_active) {
    lookup(reviewed, "reviewed_biological_label")
  } else rep(NA_character_, length(k))
  stage07_label <- lookup(stage07, "canonical_biological_label")
  if (all(is.na(stage07_label))) stage07_label <- lookup(stage07, "final_plot_label")
  stage01_label <- lookup(stage01, "ModuleLabel_Final")

  label <- reviewed_label
  source <- ifelse(!is.na(label), "active_reviewed_registry", NA_character_)
  take <- is.na(label) & !is.na(stage07_label)
  label[take] <- stage07_label[take]; source[take] <- "stage07_canonical"
  take <- is.na(label) & !is.na(stage01_label)
  label[take] <- stage01_label[take]; source[take] <- "stage01_fallback"
  take <- is.na(label)
  label[take] <- as.character(entities$entity_id)[take]
  source[take] <- "entity_id_fallback"

  confidence <- rep(NA_character_, length(k))
  if (reviewed_active && !is.null(reviewed$confidence)) {
    confidence <- lookup(reviewed, "confidence")
  }
  confidence[source != "active_reviewed_registry"] <- "automatic"

  data.frame(
    dataset = as.character(entities$dataset),
    level = as.character(entities$level),
    entity_id = as.character(entities$entity_id),
    canonical_display_label = label,
    canonical_label_source = source,
    canonical_label_confidence = confidence,
    Stage01_ModuleLabel_Final = stage01_label,
    Stage07_label = stage07_label,
    reviewed_label = reviewed_label,
    stringsAsFactors = FALSE
  )
}

# Hard invariant: one canonical display label per dataset + level + entity_id.
wal_assert_one_label_per_entity <- function(resolved,
                                            label_column = "canonical_display_label") {
  need <- c("dataset", "level", "entity_id", label_column)
  missing <- setdiff(need, names(resolved))
  if (length(missing)) {
    stop("Resolved label table is missing: ", paste(missing, collapse = ", "), ".",
         call. = FALSE)
  }
  k <- paste(resolved$dataset, resolved$level, resolved$entity_id, sep = "\r")
  split_labels <- split(as.character(resolved[[label_column]]), k)
  offenders <- names(split_labels)[
    vapply(split_labels, function(v) length(unique(v[!is.na(v)])) > 1L, logical(1))
  ]
  if (length(offenders)) {
    stop("The same dataset + entity resolves to more than one display label: ",
         paste(utils::head(gsub("\r", " / ", offenders), 5), collapse = "; "),
         ". A single artifact must never show two names for one entity.",
         call. = FALSE)
  }
  invisible(TRUE)
}

# ------------------------------------------------- hierarchy redundancy

.wal_norm_label <- function(x) {
  x <- tolower(trimws(as.character(x)))
  gsub("[^a-z0-9]+", " ", x)
}

# Flag a multi-module supermodule where the parent and >= 2 member modules
# carry effectively the same label. A REVIEW WARNING, never an automatic
# failure: sometimes a supermodule genuinely is its members.
wal_hierarchy_redundancy <- function(modules, supermodules,
                                     label_column = "proposed_final_label") {
  need_m <- c("dataset", "entity_id", "parent_entity_id", label_column)
  need_s <- c("dataset", "entity_id", label_column)
  for (nm in need_m) if (!nm %in% names(modules))
    stop("modules is missing ", nm, ".", call. = FALSE)
  for (nm in need_s) if (!nm %in% names(supermodules))
    stop("supermodules is missing ", nm, ".", call. = FALSE)

  out <- rep(NA_character_, nrow(supermodules))
  for (i in seq_len(nrow(supermodules))) {
    ds <- supermodules$dataset[[i]]; sm <- supermodules$entity_id[[i]]
    mem <- modules[modules$dataset == ds &
                     as.character(modules$parent_entity_id) == sm, , drop = FALSE]
    if (nrow(mem) < 2L) next
    parent <- .wal_norm_label(supermodules[[label_column]][[i]])
    same <- .wal_norm_label(mem[[label_column]]) == parent
    same[is.na(same)] <- FALSE
    if (sum(same) >= 2L) {
      out[[i]] <- paste0(
        "REVIEW: supermodule label matches ", sum(same), " of ", nrow(mem),
        " member modules (", paste(mem$entity_id[same], collapse = ", "),
        "); member names are not discriminative."
      )
    }
    # duplicate member names within one supermodule are also worth flagging
    dup <- .wal_norm_label(mem[[label_column]])
    dup_tab <- table(dup[nzchar(dup)])
    if (any(dup_tab >= 2L)) {
      repeated <- names(dup_tab)[dup_tab >= 2L]
      msg <- paste0("REVIEW: ", length(repeated),
                    " label(s) shared by multiple member modules of ", sm, ".")
      out[[i]] <- if (is.na(out[[i]])) msg else paste(out[[i]], msg)
    }
  }
  out
}

# ------------------------------------------------ final approval table

wal_approval_columns <- function() {
  c("dataset", "level", "entity_id", "parent_entity_id",
    "current_active_label", "proposed_final_label",
    "alternative_label_1", "alternative_label_2", "confidence",
    "evidence_class", "adjudication_action", "top_hubs_compact",
    "dominant_theme", "strongest_alternative_theme",
    "central_support_summary", "GO_support_summary", "contradiction_summary",
    "hierarchy_redundancy_warning", "bp_blind_spot_warning",
    "context_caveat", "rationale",
    "candidate_theme", "automatic_proposal_label", "algorithmic_evidence_class",
    "evidence_class_source",
    "recommended_for_activation", "human_decision")
}

# Activation readiness. Deliberately conservative: anything mixed, unresolved,
# peripheral or low-confidence is NOT recommended, regardless of how attractive
# the label reads.
wal_recommend_activation <- function(confidence, evidence_class, action) {
  conf <- tolower(trimws(as.character(confidence)))
  cls <- tolower(trimws(as.character(evidence_class)))
  act <- toupper(trimws(as.character(action)))
  blocked_class <- grepl("mixed|unresolved|peripheral", cls)
  blocked_action <- act %in% c("MIXED", "UNRESOLVED")
  blocked_keep <- act %in% "KEEP_ACTIVE_REVIEWED"
  conf %in% c("high", "moderate") & !blocked_class & !blocked_action & !blocked_keep
}

# Assemble the approval table. `human_decision` is always NA: approval is the
# reviewer's act, never this pipeline's.
wal_build_approval_table <- function(entities) {
  for (nm in c("dataset", "level", "entity_id")) {
    if (!nm %in% names(entities)) stop("entities is missing ", nm, ".", call. = FALSE)
  }
  out <- entities
  for (nm in wal_approval_columns()) {
    if (!nm %in% names(out)) out[[nm]] <- NA_character_
  }
  out$recommended_for_activation <- wal_recommend_activation(
    out$confidence, out$evidence_class, out$adjudication_action)
  out$human_decision <- NA_character_
  out$contract_version <- wal_contract_version()
  out[, c(wal_approval_columns(), "contract_version"), drop = FALSE]
}

# ------------------------------------------------ curated adjudications
#
# The manual-adjudication layer. Each entry records a decision taken by reading
# the existing evidence packet, with the specific evidence in `rationale`.
# These are PROPOSALS for a human to approve; nothing here is activated.
#
# Every entry is phenotype-blind: only GO/theme/centrality/hub evidence was
# consulted. No group contrast or differential-abundance result was used.
wal_curated_adjudications <- function() {
  rows <- list(
    # ---- neuron_neuropil: the m01 / m04 / m10 differentiation -------------
    c("neuron_neuropil", "module", "WGCNA_m01",
      "synaptic organization - postsynaptic specialization",
      "postsynaptic structural organization",
      "synaptic organization / signalling", "high",
      "Distinguished from m04/m10 by CC evidence that is exclusive to m01: postsynaptic specialization (p=3.6e-16), postsynaptic density (p=3.9e-12) and dendritic spine (p=7.6e-12). Postsynaptic terms number 37/40/24 across the all/core/top-25 sets versus effectively zero in m04 and m10; actin terms 27/28/5 versus 0/0/0 in both. BP carries 79 synaptic terms (p=3e-19) with 0.70 of top-10 hubs contributing (AUC 0.81). MF is binding-type (actin filament binding p=3.3e-09, glutamate receptor binding p=6.1e-07), in deliberate contrast to m10 which has kinase ACTIVITY. Named postsynaptic specialization rather than scaffolding: specialization is the GO term the evidence actually supports, whereas scaffolding asserts a mechanism the packet does not test. CAVEAT: 5 of the 25 top hubs are exocyst subunits (EXOC7/3/8/4/1; exocyst CC p=2.6e-07), so a vesicle-tethering component sits at the hub centre; it does not displace the label because it covers only 13/579 module proteins."),
    c("neuron_neuropil", "module", "WGCNA_m04",
      "synaptic organization - presynaptic release and excitability",
      "presynaptic vesicle release / excitability",
      "synaptic organization / signalling", "moderate",
      "Distinguished from m01/m10 by two converging axes: BP carries dense core granule localization and exocytic process alongside 41 synaptic and 33 vesicle-trafficking core terms, and the TOP-25 HUB set is enriched specifically for membrane depolarization (p=3.9e-05) and ion transport / membrane potential. Hubs UNC13A and BSN are active-zone components and CPE/CCK are dense-core-granule cargo. Confidence is moderate because the all-protein-set support is weaker (p=1.6e-04) than m01's."),
    c("neuron_neuropil", "module", "WGCNA_m10",
      "synaptic signalling - kinase/phosphatase and vesicle endocytosis",
      "synaptic organization / signalling",
      "membrane / cytoskeletal signalling", "moderate",
      "Distinguished from m01/m04 by catalytic rather than structural evidence. MF is kinase ACTIVITY (protein kinase activity p=2.5e-06, protein serine/threonine kinase activity p=7.6e-06) where m01 has kinase BINDING; CC is protein serine/threonine phosphatase complex (p=4.1e-07), COP9 signalosome (p=6.2e-04) and presynaptic endocytic zone (p=4.2e-03). A MAPK-cascade theme appears in neither m01 nor m04 (core p=3.1e-04). m10 has zero postsynaptic, zero actin and zero active-zone terms in any set, so it is neither m01 nor m04. The earlier membrane/cytoskeletal wording was dropped: kinase/phosphatase signalling and vesicle endocytosis are what the CC and MF evidence names, whereas membrane and cytoskeletal were inferred. Moderate because the all-protein set's leading theme is peripheral proteostasis (AUC 0.47) and the synaptic support arrives only via the core and top-25 sets."),
    # ---- neuron_neuropil: m02 / m07 differentiation -----------------------
    c("neuron_neuropil", "module", "WGCNA_m02",
      "mitochondrial respiration / oxidative energy metabolism",
      "mitochondrial respiration", "mitochondrial energy metabolism", "moderate",
      "The respiration subprogram is unambiguous: 46 core mitochondrial terms at p=9e-54, with aerobic respiration (p=5e-50) and energy derivation by oxidation of organic compounds (p=5e-50) as the leading individual terms, and CC enrichment for mitochondrial inner membrane. Hubs UQCRC2 (complex III), ETFA, MECR, TIMM44, HSPD1 and CKMT1 are respiratory-chain and inner-membrane proteins. Naming this respiration rather than the parent umbrella keeps it more specific than SM03. CONTRADICTION: the module is not purely respiratory - it also carries mitochondrial translation, mitochondrial gene expression and mitochondrion-organisation components, so the respiration wording is a lean, not an exclusive claim. Confidence is therefore moderate: high would be defensible only for the broader mitochondrial energy metabolism wording, which is rejected here because it would duplicate the parent SM03."),
    c("neuron_neuropil", "module", "WGCNA_m07",
      "mixed / unresolved", "mitochondrial metabolic processes",
      "acetyl-CoA metabolic process", "low",
      "The whole evidence base for this module is ONE GO term: acetyl-CoA metabolic process, BP, p=3.1e-02, 4 contributing proteins, present only in the core set. The all set has 0 significant terms, the top-25 hub set has 0, and there is no significant CC or MF in any set. Critically, the word mitochondrial has NO direct support anywhere in the packet - no mitochondrial CC term is significant - so mitochondrial metabolic processes was itself an overstatement and has been demoted to the alternative wording. The hub composition (GLS, SLC25A22, DLAT, PDK2) is suggestive of glutamate/pyruvate substrate handling, but naming from hub gene identity alone is exactly what this pass forbids. Not recommended for activation."),
    # ---- neuron_neuropil: conservative cases ------------------------------
    c("neuron_neuropil", "module", "WGCNA_m09",
      "mixed / unresolved", "membrane / cytoskeletal trafficking",
      "intracellular trafficking", "low",
      "Downgraded from the algorithmic vesicle trafficking / exocytosis proposal. The requirements for that label are not met: only 2 core and 3 all-set GO terms, no top-25 hub enrichment at all, and top-10 contribution of 0.10-0.20. MF evidence (small GTPase binding, GTPase binding) and hubs (MACF1, CYFIP1, ARFGEF2, VPS53, DYNLL2) are trafficking- and cytoskeleton-adjacent, which is why membrane / cytoskeletal trafficking is retained as an alternative, but the GO evidence does not converge. Not recommended for activation."),
    c("neuron_neuropil", "module", "WGCNA_m03",
      "vesicle coat / Golgi-ER membrane trafficking", "mixed / unresolved",
      "coated-vesicle membrane trafficking", "low",
      "P-body assembly was NOT adopted: it rests on 6 core proteins at p=2.1e-03 with 0.10 of top-10 hubs contributing. A coherent concept does exist, but it is the coat evidence, not the RNA-granule one, and it is four orders of magnitude stronger: CC membrane coat and coated membrane p=1.7e-07, vesicle coat p=3.7e-07, coated vesicle p=2.9e-05, Golgi-associated vesicle membrane p=1.3e-05 - 23 significant CC terms in the core set and 22 in the all set. BP agrees directionally (ER to Golgi vesicle-mediated transport p=2.1e-03, endosome to lysosome transport, vesicle organization). The earlier mixed / unresolved call came from reading a BP-only theme mapper; the BP terms alone are all p~1e-02 and genuinely inconclusive, which is why confidence stays LOW and this is NOT recommended for activation: the top-25 hub set has zero significant terms in any ontology, so the network centre does not carry the concept."),
    c("neuron_neuropil", "module", "WGCNA_m06",
      "unresolved", NA, NA, "low",
      "No defensible label exists. The core protein set has NO significant BP theme, and there is no significant CC or MF enrichment whatsoever. The original Proteasome Assembly term was both nonsignificant (p=0.28) and peripherally driven (AUC 0.30). Per the adjudication principle, unresolved is preferable to rescuing the next available GO term. Not recommended for activation."),
    # ---- neuron_neuropil: wording of the settled modules ------------------
    c("neuron_neuropil", "module", "WGCNA_m05",
      "vesicle trafficking / exocytosis", "vesicle trafficking / membrane fusion",
      NA, "high",
      "Biology unchanged; wording made precise. Both named aspects are separately supported in the core set: regulation of vesicle-mediated transport (p=2.1e-07) for trafficking, and exocytosis (p=3.8e-07) with 13 exocytosis/secretion terms plus regulation of exocytosis (p=9.8e-06) for release. Vesicle fusion (p=2.5e-07, 9 fusion terms) is essentially tied with exocytosis, so membrane fusion is retained as the alternative wording rather than discarded. CC is cytoplasmic vesicle membrane and endosome membrane; MF is SNARE binding and syntaxin binding; hubs VAMP7, STXBP5 and NAPA are SNARE-machinery components."),
    c("neuron_neuropil", "module", "WGCNA_m08",
      "aminoacyl-tRNA synthesis", "tRNA aminoacylation / translation", NA, "high",
      "Wording chosen on orthogonal CC and MF evidence: CC aminoacyl-tRNA synthetase multienzyme complex (p=2e-16), MF aminoacyl-tRNA ligase activity (p=2e-07) and catalytic activity acting on a tRNA (p=4e-06); BP tRNA aminoacylation for protein translation (p=2e-06) over only 9 terms. Hubs LARS1, MARS1, IARS1, RARS1 and DARS1 are synthetases. The alternative wording tRNA aminoacylation / translation is rejected as an overstatement: there is no general translation-machinery evidence beyond aminoacylation itself, so appending translation would claim more than the packet supports."),
    c("neuron_neuropil", "module", "WGCNA_m11",
      "oligodendrocyte / myelin ensheathment", "myelin ensheathment", NA, "high",
      "Replaces the raw ontology phrase Ensheathment Neurons. Core BP carries 5 myelin/ensheathment terms (p=1e-09) plus glial cell differentiation, CC is myelin sheath and compact myelin, and hubs CNP, MAG, MOG, ERMN, BCAS1 and ENPP6 are canonical oligodendrocyte/myelin proteins with 0.60 of top-10 hubs contributing."),
    c("neuron_neuropil", "module", "WGCNA_m12",
      "RNA processing / RNP", "RNA-binding protein / RNP complex", NA, "high",
      "RNP is named rather than splicing. Splicing is genuinely present - RNA splicing is the second BP term (p=5e-62), 15 splicing terms, CC spliceosomal complex p=3e-44 - but it is the smaller half of the module: CC ribonucleoprotein complex (p=1e-108), cytosolic ribosome (p=4e-58) and MF structural constituent of ribosome (p=6e-50) are orders of magnitude stronger. Naming splicing would misrepresent the large ribosomal/RNP component, so RNP is used because it covers both. MF is RNA binding. The theme carries 32 core terms at p=4e-72 with 0.90 of top-10 hubs contributing; hubs are HNRNPA3/D/K, HNRNPA2B1, DDX5, DDX39B, ELAVL1 and PTBP2. Implying splicing would over-specify."),
    c("neuron_neuropil", "module", "WGCNA_m13",
      "protein folding / chaperone activity", "protein folding / chaperone", NA,
      "moderate",
      "Chaperone activity is named on MF evidence (ATP-dependent protein folding chaperone, protein folding chaperone) and CC protein folding chaperone complex. Confidence is moderate rather than high because the BP theme rests on a single core term (p=2e-11) and the module also carries unrelated telomere/DNA-biosynthesis terms, so proteostasis in the broader sense is not claimed."),
    c("neuron_neuropil", "module", "WGCNA_m14",
      "cytoplasmic translation initiation", "cytoplasmic translation", NA, "moderate",
      "Initiation specifically IS supported by orthogonal evidence: CC cytosolic translation preinitiation complex (p=1e-13), eukaryotic 48S preinitiation complex (p=9e-13), eukaryotic 43S preinitiation complex (p=1e-12) and eIF3 complex (p=7e-12), and MF translation initiation factor activity (p=7e-15). The specificity is real: 4 initiation terms and ZERO elongation or termination terms, so cytoplasmic translation alone would understate. CONTRADICTION: a co-resident ER membrane / protein-insertion component is present (MF membrane insertase activity p=3e-03), so the module is not purely an initiation complex; confidence is moderate rather than high for that reason. The broader cytoplasmic translation wording is retained as an alternative."),
    c("neuron_neuropil", "module", "WGCNA_m15",
      "epithelial / keratinization signature", "non-neural epithelial signature",
      NA, "moderate",
      "Kept as an explicit SIGNATURE, never a cell-type claim. The literal epithelial program markers are present: CC cornified envelope, desmosome and adherens junction, with 4 core keratinization terms (p=2e-04) and hubs TGM1, FLG2, DSP, S100A14 and LYZ1. Because the structural CC markers are the literal program, keratinization-like hedging is unnecessary; the contextual caveat carries the interpretation instead."),
    # ---- neuron_soma -----------------------------------------------------
    c("neuron_soma", "module", "WGCNA_m01",
      "proteostasis / ubiquitin-proteasome", "ubiquitin-dependent protein catabolism",
      "mixed / unresolved", "low",
      "The proteasome concept is specific but weak and peripheral. CC proteasome regulatory particle, base subcomplex p=3.3e-04 with proteasome complex p=2e-02; BP ubiquitin-dependent protein catabolic process p=2e-03 over only 8 core terms. The top-25 hub set has just 2 significant terms and NEITHER is proteasomal (ATP-dependent protein folding chaperone MF p=3.6e-02, smooth endoplasmic reticulum CC p=5e-02), and no top hub (ATXN10, DGKE, STRAP, HID1, PDIA4, RYR2, DST) is a proteasome subunit. The packet records centre_supports_theme=FALSE. Downgraded from moderate to LOW and NOT recommended: a real but peripheral signal must not be promoted to a module name on the strength of 16 all-set terms."),
    c("neuron_soma", "module", "WGCNA_m02",
      "nuclear gene expression - chromatin remodelling and RNA processing",
      "nuclear RNA processing / splicing", "chromatin remodelling", "high",
      "CORRECTED from mixed / unresolved, which was an uncritical pass-through of the algorithmic coherence_class. This is the strongest module in the soma network: 492 / 553 / 119 significant terms across the all / core / top-25 sets, with n_protein_sets_supporting_theme=3 and centre_supports_theme=TRUE. Core CC nuclear protein-containing complex p=5.6e-167, chromosome p=4e-78, nuclear body p=2e-66; core BP RNA processing p=8e-143, mRNA processing p=4e-117, RNA splicing p=3e-99; core MF DNA binding p=1e-82, chromatin binding p=4e-47. The mixed_biology class reflected high theme ENTROPY in a 1836-protein module, not absence of a dominant theme. Both halves of the name are earned: the module body is nuclear RNA processing, and the hub centre is specifically chromatin remodelling (top-25 chromatin p=6.9e-09, chromatin remodeling p=2e-06, SWI/SNF superfamily-type complex p=2e-06; hubs CHD4, GATAD2B, SMARCA2, SMARCA5, RBBP4)."),
    c("neuron_soma", "module", "WGCNA_m03",
      "mixed / unresolved", "organic acid catabolic process",
      "amino acid metabolic process", "low",
      "CORRECTED to mixed. The three protein sets disagree on what the module is: the all set has 8 CC terms led by anchoring junction p=6.2e-03 and NO significant BP, the core set has 21 BP terms led by organic acid catabolic process p=5.5e-03 and NO significant CC, and the top-25 set is led by caveola p=5.3e-03. Nothing is stronger than p~5e-03, the packet records n_protein_sets_supporting_theme=1 and centre_supports_theme=FALSE. Naming the module amino acid metabolic process promoted a single weak core term over mutually inconsistent evidence, which is the failure mode this pass exists to prevent."),
    c("neuron_soma", "module", "WGCNA_m04",
      "mixed / unresolved", "cytoplasmic translation", NA, "low",
      "Algorithmic adjudication was mixed_biology and the centre did not support the translation term. Retained as mixed. Not recommended for activation."),
    c("neuron_soma", "module", "WGCNA_m05",
      "actin cytoskeleton organization", "cytoskeleton / actin-microtubule", NA,
      "high",
      "Well supported with genuine centre support, and the only soma module whose theme replicates in all three protein sets at high significance: BP actin cytoskeleton organization p=5.9e-13 (all, 38 proteins) and p=2.0e-13 (core), with the top-25 hub set independently enriched for actin nucleation p=6.9e-11 - 174 / 188 / 148 significant terms across the three sets. Wording made readable while staying specific to actin, which the evidence names directly rather than the broader cytoskeleton / actin-microtubule phrasing."),
    c("neuron_soma", "module", "WGCNA_m06",
      "mitochondrial respiration / oxidative phosphorylation",
      "mitochondrial energy metabolism", "aerobic respiration", "high",
      "CORRECTED from mixed / unresolved, which was an uncritical pass-through of the algorithmic coherence_class. The evidence is overwhelming and convergent across all three ontologies and all three protein sets (n_protein_sets_supporting_theme=3, centre_supports_theme=TRUE): core CC respiratory chain complex p=1.9e-43 and mitochondrial inner membrane p=2e-33; core BP aerobic respiration p=2e-35, oxidative phosphorylation p=1e-34, proton motive force-driven ATP synthesis p=1e-34; core MF proton transmembrane transporter activity p=9e-21. The hub centre carries it too: top-25 oxidoreductase complex p=2e-07 and aerobic respiration p=2e-07. Hubs PDHA1, DLAT, IDH3A, IDH3B, SUCLA2 and CLYBL are PDH and TCA enzymes. As in neuropil, the mixed_biology class reflected theme entropy, not an absent dominant theme."),
    c("neuron_soma", "module", "WGCNA_m07",
      "synaptic organization / signalling", "trans-synaptic signalling",
      "synaptic signalling / vesicle tethering", "high",
      "Well supported with centre support: 277 / 291 / 53 significant terms, core BP trans-synaptic signaling p=2.1e-14 over 101 proteins and core CC synaptic membrane p=1.5e-11 over 104. Distinct from soma m05 within SM02, so no member-level redundancy. NOTE for the reviewer: the single strongest hub-centre term is CC exocyst p=1.4e-12 (7 of 25 hubs), so an exocyst-dependent vesicle-tethering component sits at the centre of this module; it refines rather than contradicts the synaptic label, and the narrower wording is offered as an alternative.")
  )
  out <- as.data.frame(do.call(rbind, rows), stringsAsFactors = FALSE)
  names(out) <- c("dataset", "level", "entity_id", "proposed_final_label",
                  "alternative_label_1", "alternative_label_2", "confidence",
                  "rationale")
  out
}

# Supermodule adjudications, derived AFTER module biology. A parent keeps the
# broader umbrella only where its members genuinely share it.
wal_curated_supermodule_adjudications <- function() {
  rows <- list(
    c("neuron_neuropil", "SM02", "synaptic organization / signalling", "moderate",
      "Umbrella retained, and the evidence supports it collectively: m01, m09 and m10 all carry the synaptic theme in the core set. Members now carry distinct subprograms (m01 postsynaptic specialization, m10 kinase/phosphatase signalling and vesicle endocytosis, m09 unresolved), so the parent is genuinely broader than any member and the hierarchy is no longer redundant."),
    c("neuron_neuropil", "SM03", "mitochondrial energy metabolism", "moderate",
      "Umbrella retained and strictly broader than its members: m02 is named respiration specifically, and m07 is unresolved. Note the umbrella rests almost entirely on m02 - m07 contributes one GO term at p=3.1e-02 - so this is a one-member-supported supermodule in practice."),
    c("neuron_neuropil", "SM06", "mixed / unresolved", "low",
      "Members are m03 (vesicle coat / Golgi-ER trafficking, low confidence, no hub-centre support) and m06 (unresolved, zero enrichment anywhere). One weak member cannot name a supermodule, so no supermodule biology is claimed."),
    c("neuron_neuropil", "SM07", "mixed / unresolved", "low",
      "Five members spanning presynaptic release, vesicle fusion, aminoacyl-tRNA synthesis, chaperone activity and translation initiation. Structurally related but biologically heterogeneous; not forced into one mechanistic name."),
    c("neuron_soma", "SM01", "mixed / unresolved", "low",
      "Members are m06 (mitochondrial respiration, high confidence) and m04 (mixed / unresolved). Deliberately NOT named mitochondrial: only one of two members carries that biology, and inheriting a single member's program would misrepresent the other. The earlier hierarchy-redundancy warning on this supermodule is now resolved, because m04 and m06 no longer share a label."),
    c("neuron_soma", "SM02", "cytoskeletal and synaptic organization", "moderate",
      "Members m05 (actin cytoskeleton) and m07 (trans-synaptic signalling) are distinct but related; a compound umbrella is used because both subprograms are genuinely substantial."),
    c("neuron_soma", "SM03", "nuclear gene expression - chromatin remodelling and RNA processing",
      "high",
      "Singleton supermodule inheriting its only member, m02, whose evidence is the strongest in the soma network (core CC nuclear protein-containing complex p=5.6e-167). Parent and member necessarily share a name here; the redundancy check correctly exempts singletons."),
    c("neuron_soma", "SM04", "proteostasis / ubiquitin-proteasome", "low",
      "Singleton inheriting m01, and downgraded with it from moderate to LOW. The proteasome signal is peripheral and absent from the hub centre. This is also the least stable entity in the soma packet (cut-height stability 0.333 versus 0.833-1.0 for every other supermodule), which is an independent reason not to activate its name."),
    c("neuron_soma", "SM05", "mixed / unresolved", "low",
      "Singleton inheriting m03, corrected with it from alpha-amino acid metabolic process to mixed. The member's three protein sets disagree and nothing exceeds p~5e-03.")
  )
  out <- as.data.frame(do.call(rbind, rows), stringsAsFactors = FALSE)
  names(out) <- c("dataset", "entity_id", "proposed_final_label", "confidence",
                  "rationale")
  out$level <- "supermodule"
  out$alternative_label_1 <- NA_character_
  out$alternative_label_2 <- NA_character_
  out
}

# ------------------------------------- claims-table canonical label contract

# The WGCNA entity columns used by the biological claims table. The exported
# table names them wgcna_entity_id / wgcna_level; the intermediate collectors use
# module_or_supermodule_id / entity_level, so both spellings are accepted.
wal_claims_entity_columns <- function(claims = NULL) {
  candidates <- list(
    list(id = "wgcna_entity_id", level = "wgcna_level"),
    list(id = "module_or_supermodule_id", level = "entity_level")
  )
  if (is.null(claims)) return(candidates[[1]])
  for (cand in candidates) {
    if (all(unlist(cand) %in% names(claims))) return(cand)
  }
  candidates[[1]]
}

# Attach ONE canonical display label per dataset + WGCNA entity, plus the
# provenance columns. Rows that are not WGCNA entities are left untouched.
#
# No historical label is discarded: Stage01_ModuleLabel_Final, Stage06_label and
# Stage07_label are retained alongside so the submission artifact still records
# what each naming stage said.
attach_canonical_wgcna_display_label <- function(claims, reviewed_dir = NULL,
                                                 stage07_reader = NULL) {
  cols <- wal_claims_entity_columns(claims)
  if (!all(unlist(cols) %in% names(claims))) return(claims)

  is_entity <- !is.na(claims[[cols$id]]) & nzchar(trimws(as.character(claims[[cols$id]]))) &
    as.character(claims[[cols$level]]) %in% c("module", "supermodule")
  if (!any(is_entity)) {
    claims$canonical_display_label <- NA_character_
    claims$canonical_label_source <- NA_character_
    return(claims)
  }

  entities <- unique(data.frame(
    dataset = as.character(claims$dataset[is_entity]),
    level = as.character(claims[[cols$level]][is_entity]),
    entity_id = as.character(claims[[cols$id]][is_entity]),
    stringsAsFactors = FALSE
  ))

  reviewed <- NULL
  rd <- reviewed_dir %||% repo_path("config", "wgcna_labels")
  for (ds in unique(entities$dataset)) {
    p <- file.path(rd, paste0(ds, ".csv"))
    if (!file.exists(p)) next
    r <- utils::read.csv(p, stringsAsFactors = FALSE)
    r$dataset <- ds
    reviewed <- if (is.null(reviewed)) r else
      merge(reviewed, r, all = TRUE, sort = FALSE)
  }
  # Only an ACTIVE reviewed registry may be used. A proposal never qualifies.
  if (!is.null(reviewed) && !wal_is_active_reviewed(reviewed)) reviewed <- NULL

  stage07 <- NULL
  reader <- stage07_reader %||% function(ds) {
    p <- wgcna_interpretable_artifact("WGCNA_final_label_lookup.csv", ds)
    if (!file.exists(p)) return(NULL)
    utils::read.csv(p, stringsAsFactors = FALSE)
  }
  for (ds in unique(entities$dataset)) {
    lk <- reader(ds)
    if (is.null(lk) || !all(c("level", "entity_id") %in% names(lk))) next
    lab <- intersect(c("canonical_biological_label", "final_plot_label"), names(lk))[1]
    if (is.na(lab)) next
    z <- data.frame(dataset = ds, level = as.character(lk$level),
                    entity_id = as.character(lk$entity_id),
                    canonical_biological_label = as.character(lk[[lab]]),
                    stringsAsFactors = FALSE)
    stage07 <- if (is.null(stage07)) z else rbind(stage07, z)
  }

  stage01 <- NULL
  if ("ModuleLabel_Final" %in% names(claims)) {
    stage01 <- unique(data.frame(
      dataset = as.character(claims$dataset[is_entity]),
      level = as.character(claims[[cols$level]][is_entity]),
      entity_id = as.character(claims[[cols$id]][is_entity]),
      ModuleLabel_Final = as.character(claims$ModuleLabel_Final[is_entity]),
      stringsAsFactors = FALSE
    ))
    stage01 <- stage01[!duplicated(stage01[c("dataset", "level", "entity_id")]), ,
                       drop = FALSE]
  }

  resolved <- resolve_wgcna_display_label(entities, reviewed = reviewed,
                                          stage07 = stage07, stage01 = stage01)
  wal_assert_one_label_per_entity(resolved)

  k <- paste(as.character(claims$dataset), as.character(claims[[cols$level]]),
             as.character(claims[[cols$id]]), sep = "\r")
  rk <- paste(resolved$dataset, resolved$level, resolved$entity_id, sep = "\r")
  idx <- match(k, rk)
  pick <- function(col) {
    out <- rep(NA_character_, length(k))
    out[!is.na(idx)] <- as.character(resolved[[col]])[idx[!is.na(idx)]]
    out
  }
  claims$canonical_display_label <- pick("canonical_display_label")
  claims$canonical_label_source <- pick("canonical_label_source")
  claims$Stage01_ModuleLabel_Final <- pick("Stage01_ModuleLabel_Final")
  claims$Stage07_label <- pick("Stage07_label")
  if (!"Stage06_label" %in% names(claims)) {
    claims$Stage06_label <- if ("cleaned_biological_label" %in% names(claims)) {
      as.character(claims$cleaned_biological_label)
    } else NA_character_
  }
  claims
}

# Hard invariant for the submission artifact.
assert_one_canonical_label_per_wgcna_entity <- function(claims) {
  cols <- wal_claims_entity_columns(claims)
  if (!all(c(unlist(cols), "canonical_display_label") %in% names(claims))) {
    return(invisible(TRUE))
  }
  keep <- !is.na(claims$canonical_display_label)
  if (!any(keep)) return(invisible(TRUE))
  sub <- data.frame(
    dataset = as.character(claims$dataset[keep]),
    level = as.character(claims[[cols$level]][keep]),
    entity_id = as.character(claims[[cols$id]][keep]),
    canonical_display_label = as.character(claims$canonical_display_label[keep]),
    stringsAsFactors = FALSE
  )
  wal_assert_one_label_per_entity(sub)
}

# ------------------------------------------------------- activation rules
#
# The activation contract, stated once, in order. This function DEFINES the
# rules; it never applies them. Activation is a human act performed outside
# this pipeline, and deliberately so: the whole point of the approval table is
# that a machine proposes and a person decides.
wal_activation_rules <- function() {
  data.frame(
    step = 1:8,
    rule_id = c("R1_human_decision", "R2_scope", "R3_registry_file",
                "R4_registry_fields", "R5_identity_revalidation",
                "R6_no_id_change", "R7_single_resolver", "R8_consumer_refresh"),
    rule = c(
      "A row is eligible only when a named reviewer has written APPROVE, APPROVE_WITH_EDIT or REJECT into human_decision. recommended_for_activation is advisory and never sufficient on its own.",
      "Rows whose evidence_class is mixed, unresolved or peripheral, or whose confidence is low, stay unlabelled. 'mixed / unresolved' is a legitimate final answer, not a gap to be filled.",
      "Approved labels are promoted by hand into config/wgcna_labels/<dataset>.csv. No pipeline script may write that file; the proposal files under results/reviewer_audit/ are inputs to a human, not to the registry.",
      "The registry row must carry adjudication_status = 'reviewed' and a real reviewer name. proposal_prepared_by = 'automated_evidence_audit' with reviewer = NA can never satisfy wal_is_active_reviewed().",
      "Before a registry is honoured, Stage 07 re-validates it against current Stage-01 membership by dataset + level + entity_id. A stale registry fails loudly rather than mislabelling a changed network.",
      "Activation changes names only. ModuleID and SupermoduleID are immutable; the identity contract remains the sole membership authority.",
      "Every consumer resolves its display name through resolve_wgcna_display_label(), so one entity can never show two names across figures, tables and the claims artifact.",
      "After activation, regenerate the label-consuming artifacts and re-run the label test suite. Figures are migrated only once the registry is active and green - not as part of preparing this proposal."
    ),
    executed_by_this_script = FALSE,
    stringsAsFactors = FALSE
  )
}

# ------------------------------------------- side-by-side module comparison
#
# The comparison groups that manual adjudication had to separate: modules that
# the automatic system gave the same name. Declared explicitly so the artifact
# is reproducible and the reviewer sees exactly which calls were contested.
wal_comparison_groups <- function() {
  list(
    list(group = "neuropil_synaptic_m01_m04_m10", dataset = "neuron_neuropil",
         members = c("WGCNA_m01", "WGCNA_m04", "WGCNA_m10"),
         collision = "synaptic organization / signalling"),
    list(group = "neuropil_mitochondrial_m02_m07", dataset = "neuron_neuropil",
         members = c("WGCNA_m02", "WGCNA_m07"),
         collision = "mitochondrial energy metabolism"),
    list(group = "neuropil_weak_m03_m06_m09", dataset = "neuron_neuropil",
         members = c("WGCNA_m03", "WGCNA_m06", "WGCNA_m09"),
         collision = "thin / mixed evidence")
  )
}

.wal_compact <- function(x, n = 8L, width = 300L) {
  x <- as.character(x)
  x <- x[!is.na(x) & nzchar(x)]
  if (!length(x)) return("[none]")
  substr(paste(utils::head(x, n), collapse = "; "), 1L, width)
}

# One tidy row per group + module + attribute. Long format so a group can have
# any number of members; the workbook pivots it wide for side-by-side reading.
wal_module_comparison <- function(themes, hubs, go_all, go_core, go_top25,
                                  groups = wal_comparison_groups()) {
  out <- list()
  emit <- function(g, m, attr, val) {
    out[[length(out) + 1L]] <<- data.frame(
      comparison_group = g$group, dataset = g$dataset, module_id = m,
      colliding_automatic_label = g$collision, attribute = attr,
      value = val, stringsAsFactors = FALSE)
  }
  go_pick <- function(tbl, ds, m, onto, n = 6L) {
    if (is.null(tbl) || !nrow(tbl)) return("[none]")
    z <- tbl[tbl$dataset == ds & tbl$ModuleID == m & tbl$Ontology == onto, , drop = FALSE]
    if (!nrow(z)) return("[no significant term]")
    z <- z[order(z$p.adjust), , drop = FALSE]
    .wal_compact(sprintf("%s (p=%.1e)", z$Description, z$p.adjust), n)
  }
  theme_set <- function(ds, m, set, n = 5L) {
    z <- themes[themes$dataset == ds & themes$ModuleID == m &
                  themes$protein_set == set, , drop = FALSE]
    if (!nrow(z)) return("[no theme]")
    z <- z[order(z$best_p_adjust), , drop = FALSE]
    .wal_compact(sprintf("%s (n=%d, p=%.1e)", z$theme, z$n_supporting_go_terms,
                         z$best_p_adjust), n)
  }

  for (g in groups) {
    ds <- g$dataset
    # proteins supporting each member's leading theme, for the distinguishing pass
    lead_prots <- list()
    for (m in g$members) {
      z <- themes[themes$dataset == ds & themes$ModuleID == m &
                    themes$protein_set == "core_kME_0.6", , drop = FALSE]
      if (!nrow(z)) z <- themes[themes$dataset == ds & themes$ModuleID == m, , drop = FALSE]
      z <- z[order(z$best_p_adjust), , drop = FALSE]
      lead_prots[[m]] <- if (nrow(z)) {
        trimws(unlist(strsplit(as.character(z$contributing_hub_symbols[[1]]), "[;,/]")))
      } else character()
    }
    for (m in g$members) {
      h <- hubs[hubs$dataset == ds & hubs$ModuleID == m, , drop = FALSE]
      h <- h[order(h$rank), , drop = FALSE]
      emit(g, m, "top_25_hubs_with_abs_kME",
           .wal_compact(sprintf("%s(%.2f)", h$GeneSymbol, h$abs_kME), 25L, 600L))
      emit(g, m, "go_bp_themes_all", theme_set(ds, m, "all"))
      emit(g, m, "go_bp_themes_core_kME_0.6", theme_set(ds, m, "core_kME_0.6"))
      emit(g, m, "go_bp_themes_top_hub_25", theme_set(ds, m, "top_hub_25"))
      emit(g, m, "go_cc", go_pick(go_core, ds, m, "CC"))
      emit(g, m, "go_mf", go_pick(go_core, ds, m, "MF"))
      emit(g, m, "go_bp_top_terms_all_set", go_pick(go_all, ds, m, "BP"))
      emit(g, m, "go_bp_top_terms_top25_set", go_pick(go_top25, ds, m, "BP"))

      z <- themes[themes$dataset == ds & themes$ModuleID == m, , drop = FALSE]
      z <- z[order(z$best_p_adjust), , drop = FALSE]
      if (nrow(z)) {
        emit(g, m, "leading_theme", as.character(z$theme[[1]]))
        emit(g, m, "centrality_support_of_leading_theme",
             sprintf("top10_frac=%s; top25_frac=%s; median_abs_kME=%s; centrality_AUC=%s",
                     format(z$fraction_top10_contributing[[1]], digits = 2),
                     format(z$fraction_top25_contributing[[1]], digits = 2),
                     format(z$median_contributor_abs_kME[[1]], digits = 2),
                     format(z$contributor_centrality_auc[[1]], digits = 2)))
        emit(g, m, "proteins_supporting_leading_theme",
             .wal_compact(lead_prots[[m]], 15L, 400L))
        alt <- z[as.character(z$theme) != as.character(z$theme[[1]]), , drop = FALSE]
        emit(g, m, "strongest_alternative_theme",
             if (nrow(alt)) sprintf("%s (n=%d, p=%.1e)", alt$theme[[1]],
                                    alt$n_supporting_go_terms[[1]], alt$best_p_adjust[[1]])
             else "[none]")
      } else {
        emit(g, m, "leading_theme", "[no theme]")
        emit(g, m, "centrality_support_of_leading_theme", "[no theme]")
        emit(g, m, "proteins_supporting_leading_theme", "[none]")
        emit(g, m, "strongest_alternative_theme", "[none]")
      }
      others <- unique(unlist(lead_prots[setdiff(g$members, m)]))
      emit(g, m, "proteins_distinguishing_from_group",
           .wal_compact(setdiff(lead_prots[[m]], others), 15L, 400L))
      emit(g, m, "themes_unique_to_this_module_in_group",
           .wal_compact(setdiff(
             unique(themes$theme[themes$dataset == ds & themes$ModuleID == m]),
             unique(themes$theme[themes$dataset == ds &
                                   themes$ModuleID %in% setdiff(g$members, m)])), 6L))
    }
  }
  do.call(rbind, out)
}

# ---------------------------------------------------- BP blind-spot detector
#
# The Stage-15 theme layer is built from BP terms only. An entity whose biology
# is carried by CC or MF evidence can therefore be classed mixed/unresolved
# while the packet's own GO tables name it clearly. That is not a hypothetical:
# it is what mis-labelled neuropil m03 and soma m02/m06 before manual review.
#
# Advisory only, like the hierarchy check. It never changes a label; it tells a
# reviewer where the automatic classification had no way to see the evidence.
wal_bp_blind_spot <- function(rows, go_core, p_threshold = 1e-04) {
  out <- rep(NA_character_, nrow(rows))
  if (is.null(go_core) || !nrow(go_core)) return(out)
  lab <- tolower(paste(rows$proposed_final_label, rows$algorithmic_evidence_class))
  for (i in seq_len(nrow(rows))) {
    if (!grepl("mixed|unresolved", lab[[i]])) next
    z <- go_core[go_core$dataset == rows$dataset[[i]] &
                   go_core$ModuleID == rows$entity_id[[i]] &
                   go_core$Ontology %in% c("CC", "MF"), , drop = FALSE]
    if (!nrow(z)) next
    z <- z[order(z$p.adjust), , drop = FALSE]
    if (z$p.adjust[[1]] >= p_threshold) next
    out[[i]] <- sprintf(
      paste0("REVIEW: classed mixed/unresolved by a BP-only theme layer, but the ",
             "core set carries %d significant CC/MF terms led by '%s' (%s, p=%.1e). ",
             "Check whether the biology is simply not visible in BP."),
      nrow(z), z$Description[[1]], z$Ontology[[1]], z$p.adjust[[1]])
  }
  out
}

# ------------------------------------------- conservative unapproved proposals
#
# Safety rule for rows this pipeline is PROPOSING (not rows that already carry an
# active reviewed label). If a proposal is low confidence and therefore not
# recommended for activation, its PRIMARY wording must itself be conservative:
# a reviewer skimming the primary column must not read a specific mechanism that
# the evidence was too weak to activate.
#
# The specific theme is never lost. It moves to candidate_theme and to the
# alternative wording, so the evidence and the reading remain on the row.
#
# Rows with adjudication_action == "KEEP_ACTIVE_REVIEWED" are EXEMPT: those are
# human-reviewed labels already in force, and rewriting them here would be
# exactly the automatic registry edit the framework forbids.
wal_conservative_label <- function() "mixed / unresolved"

wal_is_conservative_label <- function(x) {
  tolower(trimws(as.character(x))) %in%
    c("mixed / unresolved", "mixed/unresolved", "unresolved", "")
}

wal_enforce_conservative_unapproved <- function(rows) {
  need <- c("proposed_final_label", "confidence", "adjudication_action")
  for (nm in need) if (!nm %in% names(rows))
    stop("rows is missing ", nm, ".", call. = FALSE)
  if (!"candidate_theme" %in% names(rows)) rows$candidate_theme <- NA_character_
  if (!"alternative_label_1" %in% names(rows)) rows$alternative_label_1 <- NA_character_
  if (!"alternative_label_2" %in% names(rows)) rows$alternative_label_2 <- NA_character_

  conf <- tolower(trimws(as.character(rows$confidence)))
  act <- toupper(trimws(as.character(rows$adjudication_action)))
  hit <- conf %in% "low" & !act %in% "KEEP_ACTIVE_REVIEWED" &
    !wal_is_conservative_label(rows$proposed_final_label)
  hit[is.na(hit)] <- FALSE
  if (!any(hit)) return(rows)

  demoted <- as.character(rows$proposed_final_label)[hit]
  rows$candidate_theme[hit] <- demoted
  # keep the demoted wording as the leading alternative, without losing an
  # existing alternative: shift it down if slot 2 is free.
  a1 <- as.character(rows$alternative_label_1)[hit]
  a2 <- as.character(rows$alternative_label_2)[hit]
  move <- (is.na(a2) | !nzchar(a2)) & !is.na(a1) & nzchar(a1) & a1 != demoted
  a2[move] <- a1[move]
  a1 <- demoted
  # an alternative that merely repeats the new conservative primary carries no
  # information for the reviewer, so drop it rather than display a duplicate.
  a2[wal_is_conservative_label(a2)] <- NA_character_
  rows$alternative_label_1[hit] <- a1
  rows$alternative_label_2[hit] <- a2
  rows$proposed_final_label[hit] <- wal_conservative_label()
  rows$adjudication_action[hit] <- "MIXED"
  rows$rationale[hit] <- paste0(
    "PRIMARY PROPOSAL HELD CONSERVATIVE. The evidence-based reading is retained in ",
    "candidate_theme and alternative_label_1, but the primary wording is '",
    wal_conservative_label(), "' because the adjudicated confidence is low and the ",
    "row is not recommended for activation. ", as.character(rows$rationale)[hit])
  rows
}
