#!/usr/bin/env Rscript

# Generate the architecture contracts that a new contributor needs in order to
# find the script that owns a given analysis:
#
#   docs/ANALYSIS_ENTRYPOINTS.md  one row per canonical analysis area
#   docs/RESULTS_OWNERSHIP.md     one producing analysis per result family
#
# Both are derived from pipeline.yml so they cannot drift from the registry.

source(file.path("R", "paths.R"))
source(repo_path("R", "dataset_config.R"))
source(repo_path("R", "pipeline_registry.R"))

registry <- read_pipeline_registry(repo_path("pipeline.yml"))
steps <- pipeline_steps(registry, pipeline_stage_names(registry),
                        dataset = "all", include_unsupported = TRUE)
steps <- steps[!duplicated(steps$script), , drop = FALSE]

## Analysis identity comes from the analysis/ directory a script lives in.
area_of <- function(script) {
  m <- regmatches(script, regexpr("^analysis/[0-9]{2}_[A-Za-z_]+", script))
  if (!length(m) || !nzchar(m)) return(NA_character_)
  sub("^analysis/", "", m)
}
steps$area <- vapply(steps$script, area_of, character(1))

AREA_TITLE <- c(
  "01_preprocessing"        = "Preprocessing and identifier mapping",
  "02_qc"                   = "Quality control and marker fidelity",
  "03_spatial_validation"   = "Spatial systems validation, bilateral QC and CA2-SLM robustness",
  "04_differential_abundance" = "Differential abundance and enrichment",
  "05_wgcna"                = "WGCNA modules and supermodules",
  "06_gsea"                 = "Cell-type enrichment (EWCE/GSEA)",
  "07_spatial_networks"     = "Spatial and differential networks",
  "08_integration"          = "Biological integration and behaviour coupling",
  "09_publication_exports"  = "Publication source data and PRIDE export"
)

first_n <- function(x, n = 3L) {
  x <- unlist(strsplit(paste(x, collapse = "; "), ";", fixed = TRUE))
  x <- trimws(x[nzchar(trimws(x))])
  if (!length(x)) return("-")
  out <- paste0("`", head(unique(x), n), "`", collapse = ", ")
  if (length(unique(x)) > n) out <- paste0(out, ", +", length(unique(x)) - n, " more")
  out
}

## ------------------------------------------------------ ANALYSIS_ENTRYPOINTS
lines <- c(
  "# Canonical analysis entrypoints",
  "",
  "Generated by `tools/generate_architecture_docs.R` from `pipeline.yml`.",
  "Do not hand-edit.",
  "",
  "`pipeline.yml` remains the sole execution-order authority. This document",
  "answers a different question: which script owns a given analysis.",
  "",
  paste("Manuscript rendering is intentionally not listed here. It lives in the",
        "Exp9_manuscript repository and consumes the frozen bundles under",
        "`results/publication_source_data/`."),
  ""
)

for (a in names(AREA_TITLE)) {
  s <- steps[!is.na(steps$area) & steps$area == a, , drop = FALSE]
  if (!nrow(s)) next
  req <- s[s$required %in% TRUE, , drop = FALSE]
  lead <- if (nrow(req)) req$script[1] else s$script[1]
  lines <- c(lines,
    paste0("## ", a),
    "",
    paste0("**", AREA_TITLE[[a]], "**"),
    "",
    paste0("| field | value |"),
    paste0("| --- | --- |"),
    paste0("| analysis_id | `", a, "` |"),
    paste0("| entrypoint | `", lead, "` |"),
    paste0("| scripts in area | ", nrow(s), " (", sum(s$required %in% TRUE), " required) |"),
    paste0("| inputs | ", first_n(s$consumes_required), " |"),
    paste0("| primary_outputs | ", first_n(s$produces), " |"),
    paste0("| required_config | ", first_n(s$env), " |"),
    paste0("| dependency_analysis | ", paste0("`", unique(s$stage), "`", collapse = ", "), " |"),
    paste0("| publication_source_outputs | ",
           if (any(grepl("source_data", s$produces))) "`results/source_data/**`" else "-", " |"),
    "",
    "Scripts:",
    "",
    paste0("- `", s$script, "` - stage `", s$stage, "`, scope `", s$scope, "`"),
    ""
  )
}
writeLines(lines, repo_path("docs", "ANALYSIS_ENTRYPOINTS.md"), useBytes = TRUE)
cat("wrote docs/ANALYSIS_ENTRYPOINTS.md\n")

## -------------------------------------------------------- RESULTS_OWNERSHIP
## A result family is the first three path components of a produced artefact,
## e.g. results/tables/05_wgcna. Exactly one analysis should produce each.
fam_of <- function(x) {
  p <- unlist(strsplit(paste(x, collapse = ";"), ";", fixed = TRUE))
  p <- trimws(p)
  p <- p[grepl("^results/", p)]
  if (!length(p)) return(character(0))
  unique(vapply(strsplit(p, "/", fixed = TRUE), function(q) {
    paste(utils::head(q, min(3L, length(q))), collapse = "/")
  }, character(1)))
}

own <- list()
for (i in seq_len(nrow(steps))) {
  for (f in fam_of(steps$produces[i])) {
    own[[f]] <- unique(c(own[[f]], steps$script[i]))
  }
}
fams <- sort(names(own))

rl <- c(
  "# Canonical results ownership",
  "",
  "Generated by `tools/generate_architecture_docs.R` from `pipeline.yml`.",
  "Do not hand-edit.",
  "",
  paste("Each result family below is listed with every registered script that",
        "declares it in `produces`. A family with more than one producer is a",
        "coordination point, not automatically a defect: several scripts",
        "legitimately write sibling files into one stage directory. What must",
        "not happen is two scripts writing the *same* canonical file."),
  "",
  "| result family | producing analyses |",
  "| --- | --- |"
)
for (f in fams) {
  rl <- c(rl, paste0("| `", f, "` | ",
                     paste0("`", own[[f]], "`", collapse = "<br>"), " |"))
}

multi <- fams[vapply(fams, function(f) length(own[[f]]) > 1L, logical(1))]
rl <- c(rl, "",
  "## Families with more than one registered producer",
  "",
  if (length(multi)) paste0("- `", multi, "` (", vapply(multi, function(f) length(own[[f]]), integer(1)), " scripts)")
  else "None.",
  "",
  "## Publication source data",
  "",
  paste("`results/publication_source_data/<publication_id>/` is the only",
        "interface the manuscript repository reads. It is written by",
        "`analysis/09_publication_exports/` and carries a manifest with the",
        "producing commit and a sha256 per file. Nothing else in this",
        "repository may write into it."),
  ""
)
writeLines(rl, repo_path("docs", "RESULTS_OWNERSHIP.md"), useBytes = TRUE)
cat("wrote docs/RESULTS_OWNERSHIP.md\n")
cat("result families:", length(fams), " multi-producer:", length(multi), "\n")
