# ================================================================
# Differential spatial network analysis
# ================================================================
# Purpose:
#   Compare group-specific layer/region similarity networks generated by
#   Analysis/network_spatial_relations.r and quantify network rewiring.
#
# Required first step:
#   Run Analysis/network_spatial_relations.r with run_group_specific_networks = TRUE.
#
# Main outputs:
#   - Edge-level delta tables for CON vs RES, CON vs SUS, RES vs SUS
#   - Gain/loss/strengthened/weakened edge calls
#   - Node-level rewiring summaries
#   - Differential network plots
#   - Cytoscape-compatible node/edge CSV files
# ================================================================

required_pkgs <- c("dplyr", "tidyr", "stringr", "purrr", "tibble", "ggplot2", "igraph", "ggraph", "openxlsx", "svglite")
missing <- required_pkgs[!vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing) > 0) install.packages(missing, repos = "https://cloud.r-project.org")
invisible(lapply(required_pkgs, library, character.only = TRUE))

params <- list(
  #spatial_rds = "S:/Lab_Member/Tobi/Experiments/Exp9_Social-Stress/proteomics/Results/network_spatial_relations/04_Logs/network_spatial_relations_objects.rds",
  spatial_rds = "/Users/tobiaspohl/Documents/pRoteomics/Results/network_spatial_relations/04_Logs/network_spatial_relations_objects.rds",
  #output_dir = "S:/Lab_Member/Tobi/Experiments/Exp9_Social-Stress/proteomics/Results/differential_networks",
  output_dir = "/Users/tobiaspohl/Documents/pRoteomics/Results/differential_networks",
  group_order = c("CON", "RES", "SUS"),
  comparisons = list(c("CON", "RES"), c("CON", "SUS"), c("RES", "SUS")),
  edge_presence_abs_r = 0.60,
  delta_abs_r_threshold = 0.20,
  plot_min_abs_delta = 0.20
)

message2 <- function(...) message(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), " | ", ...)
safe_name <- function(x) stringr::str_replace_all(x, "[^A-Za-z0-9_\\-]+", "_")

make_dirs <- function(base_dir) {
  dirs <- list(
    base = base_dir,
    tables = file.path(base_dir, "01_Tables"),
    figures = file.path(base_dir, "02_Figures"),
    networks = file.path(base_dir, "03_Network_Files"),
    logs = file.path(base_dir, "04_Logs")
  )
  invisible(lapply(dirs, dir.create, recursive = TRUE, showWarnings = FALSE))
  dirs
}

get_group_cor_matrix <- function(obj, group) {
  if (is.null(obj$group_specific) || is.null(obj$group_specific[[group]])) return(NULL)
  obj$group_specific[[group]]$spearman$cor_mat
}

matrix_to_edges <- function(cor_mat, group) {
  units <- colnames(cor_mat)
  expand.grid(Source = units, Target = units, stringsAsFactors = FALSE) %>%
    as_tibble() %>%
    filter(Source < Target) %>%
    rowwise() %>%
    mutate(SpearmanR = cor_mat[Source, Target]) %>%
    ungroup() %>%
    mutate(Group = group, AbsSpearmanR = abs(SpearmanR))
}

compare_edge_sets <- function(edges_a, edges_b, group_a, group_b, params) {
  ea <- edges_a %>% transmute(Source, Target, R_A = SpearmanR, AbsR_A = AbsSpearmanR)
  eb <- edges_b %>% transmute(Source, Target, R_B = SpearmanR, AbsR_B = AbsSpearmanR)

  full_join(ea, eb, by = c("Source", "Target")) %>%
    mutate(
      Group_A = group_a,
      Group_B = group_b,
      DeltaR = R_B - R_A,
      AbsDeltaR = abs(DeltaR),
      Present_A = AbsR_A >= params$edge_presence_abs_r,
      Present_B = AbsR_B >= params$edge_presence_abs_r,
      EdgeClass = case_when(
        Present_A & !Present_B ~ "lost_in_B",
        !Present_A & Present_B ~ "gained_in_B",
        Present_A & Present_B & DeltaR >= params$delta_abs_r_threshold ~ "strengthened_in_B",
        Present_A & Present_B & DeltaR <= -params$delta_abs_r_threshold ~ "weakened_in_B",
        Present_A & Present_B ~ "preserved",
        TRUE ~ "weak_in_both"
      ),
      DirectionChange = case_when(
        sign(R_A) != sign(R_B) & abs(R_A) >= params$edge_presence_abs_r & abs(R_B) >= params$edge_presence_abs_r ~ "sign_flip_strong_edges",
        sign(R_A) != sign(R_B) ~ "sign_flip_weak_edge",
        TRUE ~ "same_sign"
      )
    ) %>%
    arrange(desc(AbsDeltaR))
}

node_rewiring_summary <- function(diff_edges) {
  bind_rows(
    diff_edges %>% transmute(Node = Source, EdgeClass, AbsDeltaR, DeltaR),
    diff_edges %>% transmute(Node = Target, EdgeClass, AbsDeltaR, DeltaR)
  ) %>%
    group_by(Node) %>%
    summarise(
      N_Edges = n(),
      N_Gained = sum(EdgeClass == "gained_in_B", na.rm = TRUE),
      N_Lost = sum(EdgeClass == "lost_in_B", na.rm = TRUE),
      N_Strengthened = sum(EdgeClass == "strengthened_in_B", na.rm = TRUE),
      N_Weakened = sum(EdgeClass == "weakened_in_B", na.rm = TRUE),
      MeanAbsDeltaR = mean(AbsDeltaR, na.rm = TRUE),
      MaxAbsDeltaR = max(AbsDeltaR, na.rm = TRUE),
      NetDeltaR = sum(DeltaR, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    arrange(desc(MaxAbsDeltaR), desc(MeanAbsDeltaR))
}

plot_differential_network <- function(diff_edges, outfile, title, params) {
  plot_edges <- diff_edges %>%
    filter(AbsDeltaR >= params$plot_min_abs_delta) %>%
    filter(EdgeClass != "weak_in_both")

  if (nrow(plot_edges) == 0) {
    warning("No differential edges to plot for ", title)
    return(invisible(NULL))
  }

  nodes <- unique(c(plot_edges$Source, plot_edges$Target)) %>%
    tibble::tibble(name = .)

  g <- igraph::graph_from_data_frame(
    plot_edges %>% transmute(from = Source, to = Target, AbsDeltaR, DeltaR, EdgeClass),
    directed = FALSE,
    vertices = nodes
  )

  p <- ggraph::ggraph(g, layout = "fr") +
    ggraph::geom_edge_link(aes(width = AbsDeltaR, linetype = EdgeClass, alpha = AbsDeltaR), colour = "grey35") +
    ggraph::geom_node_point(shape = 21, fill = "white", colour = "black", size = 4, stroke = 0.4) +
    ggraph::geom_node_text(aes(label = name), repel = TRUE, size = 2.8) +
    ggraph::scale_edge_width(range = c(0.2, 1.8), guide = "none") +
    ggraph::scale_edge_alpha(range = c(0.25, 0.9), guide = "none") +
    ggplot2::labs(title = title) +
    ggplot2::theme_void(base_size = 8) +
    ggplot2::theme(plot.title = element_text(hjust = 0.5, face = "bold"))

  ggplot2::ggsave(outfile, p, width = 150, height = 120, units = "mm", device = svglite::svglite)
  invisible(p)
}

write_graphml <- function(edges, nodes, outfile) {
  if (nrow(edges) == 0) return(invisible(NULL))
  g <- igraph::graph_from_data_frame(edges %>% rename(from = Source, to = Target), directed = FALSE, vertices = nodes)
  igraph::write_graph(g, outfile, format = "graphml")
}

# -------------------------------
# Main
# -------------------------------
dirs <- make_dirs(params$output_dir)
log_file <- file.path(dirs$logs, paste0("differential_networks_run_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".txt"))
sink(log_file, split = TRUE)
on.exit(sink(), add = TRUE)

message2("Starting differential spatial network analysis")
if (!file.exists(params$spatial_rds)) stop("spatial_rds not found. Run network_spatial_relations.r first: ", params$spatial_rds)
obj <- readRDS(params$spatial_rds)

all_group_edges <- purrr::map_dfr(params$group_order, function(grp) {
  mat <- get_group_cor_matrix(obj, grp)
  if (is.null(mat)) return(tibble())
  matrix_to_edges(mat, grp)
})

if (nrow(all_group_edges) == 0) stop("No group-specific correlation matrices found in spatial RDS.")
utils::write.csv(all_group_edges, file.path(dirs$tables, "all_group_edges_long.csv"), row.names = FALSE)

all_diff <- list()
all_node <- list()
wb <- openxlsx::createWorkbook()
openxlsx::addWorksheet(wb, "All_Group_Edges")
openxlsx::writeData(wb, "All_Group_Edges", all_group_edges)

for (cmp in params$comparisons) {
  group_a <- cmp[1]
  group_b <- cmp[2]
  message2("Comparing ", group_a, " vs ", group_b)

  edges_a <- all_group_edges %>% filter(Group == group_a)
  edges_b <- all_group_edges %>% filter(Group == group_b)
  if (nrow(edges_a) == 0 || nrow(edges_b) == 0) next

  diff_edges <- compare_edge_sets(edges_a, edges_b, group_a, group_b, params)
  node_summary <- node_rewiring_summary(diff_edges)
  label <- paste0(group_a, "_vs_", group_b)

  utils::write.csv(diff_edges, file.path(dirs$tables, paste0(label, "_edge_rewiring.csv")), row.names = FALSE)
  utils::write.csv(node_summary, file.path(dirs$tables, paste0(label, "_node_rewiring.csv")), row.names = FALSE)

  plot_differential_network(
    diff_edges,
    file.path(dirs$figures, paste0(label, "_differential_network.svg")),
    paste0("Spatial network rewiring: ", group_a, " vs ", group_b),
    params
  )

  cyt_edges <- diff_edges %>%
    filter(AbsDeltaR >= params$plot_min_abs_delta, EdgeClass != "weak_in_both") %>%
    transmute(Source, Target, DeltaR, AbsDeltaR, EdgeClass, DirectionChange, R_A, R_B)
  cyt_nodes <- unique(c(cyt_edges$Source, cyt_edges$Target)) %>% tibble::tibble(name = .) %>%
    left_join(node_summary, by = c("name" = "Node"))

  utils::write.csv(cyt_edges, file.path(dirs$networks, paste0(label, "_cytoscape_edges.csv")), row.names = FALSE)
  utils::write.csv(cyt_nodes, file.path(dirs$networks, paste0(label, "_cytoscape_nodes.csv")), row.names = FALSE)
  write_graphml(cyt_edges, cyt_nodes, file.path(dirs$networks, paste0(label, ".graphml")))

  openxlsx::addWorksheet(wb, paste0(label, "_Edges"))
  openxlsx::writeData(wb, paste0(label, "_Edges"), diff_edges)
  openxlsx::addWorksheet(wb, paste0(label, "_Nodes"))
  openxlsx::writeData(wb, paste0(label, "_Nodes"), node_summary)

  all_diff[[label]] <- diff_edges
  all_node[[label]] <- node_summary
}

summary_tbl <- purrr::imap_dfr(all_diff, function(df, label) {
  df %>%
    count(EdgeClass, name = "N") %>%
    mutate(Comparison = label) %>%
    select(Comparison, EdgeClass, N)
})

utils::write.csv(summary_tbl, file.path(dirs$tables, "rewiring_summary_counts.csv"), row.names = FALSE)
openxlsx::addWorksheet(wb, "Summary")
openxlsx::writeData(wb, "Summary", summary_tbl)
openxlsx::saveWorkbook(wb, file.path(dirs$tables, "differential_networks_summary.xlsx"), overwrite = TRUE)

saveRDS(
  list(params = params, all_group_edges = all_group_edges, differential_edges = all_diff, node_rewiring = all_node, summary = summary_tbl, sessionInfo = sessionInfo()),
  file.path(dirs$logs, "differential_networks_objects.rds")
)

message2("Finished differential spatial network analysis")
message2("Caution: rewiring is descriptive unless supported by bootstrap stability or independent validation.")
